//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.requests;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import org.iaea._2012.irix.format.base.FreeTextType;
import org.w3c.dom.Element;


/**
 * <p>Java class for RequestReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestReferenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RequestingOrganisation" type="{http://www.iaea.org/2012/IRIX/Format/Base}OrganisationIdentifierType" minOccurs="0"/>
 *         &lt;element name="DateAndTimeOfRequest" type="{http://www.iaea.org/2012/IRIX/Format/Base}DateTimeType" minOccurs="0"/>
 *         &lt;element name="RequestUUID" type="{http://www.iaea.org/2012/IRIX/Format/Base}UUIDType" minOccurs="0"/>
 *         &lt;element name="TypeOfRequest" type="{http://www.iaea.org/2012/IRIX/Format/Requests}TypeOfRequestType" minOccurs="0"/>
 *         &lt;element name="RequestSubject" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;any processContents='skip' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RequestText" type="{http://www.iaea.org/2012/IRIX/Format/Base}FreeTextType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestReferenceType", propOrder = {
    "requestingOrganisation",
    "dateAndTimeOfRequest",
    "requestUUID",
    "typeOfRequest",
    "requestSubject",
    "any",
    "requestText"
})
public class RequestReferenceType {

    @XmlElement(name = "RequestingOrganisation")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String requestingOrganisation;
    @XmlElement(name = "DateAndTimeOfRequest")
    protected XMLGregorianCalendar dateAndTimeOfRequest;
    @XmlElement(name = "RequestUUID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String requestUUID;
    @XmlElement(name = "TypeOfRequest")
    protected TypeOfRequestType typeOfRequest;
    @XmlElement(name = "RequestSubject")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String requestSubject;
    @XmlAnyElement
    protected List<Element> any;
    @XmlElement(name = "RequestText")
    protected FreeTextType requestText;

    /**
     * Gets the value of the requestingOrganisation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestingOrganisation() {
        return requestingOrganisation;
    }

    /**
     * Sets the value of the requestingOrganisation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestingOrganisation(String value) {
        this.requestingOrganisation = value;
    }

    /**
     * Gets the value of the dateAndTimeOfRequest property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateAndTimeOfRequest() {
        return dateAndTimeOfRequest;
    }

    /**
     * Sets the value of the dateAndTimeOfRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateAndTimeOfRequest(XMLGregorianCalendar value) {
        this.dateAndTimeOfRequest = value;
    }

    /**
     * Gets the value of the requestUUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestUUID() {
        return requestUUID;
    }

    /**
     * Sets the value of the requestUUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestUUID(String value) {
        this.requestUUID = value;
    }

    /**
     * Gets the value of the typeOfRequest property.
     * 
     * @return
     *     possible object is
     *     {@link TypeOfRequestType }
     *     
     */
    public TypeOfRequestType getTypeOfRequest() {
        return typeOfRequest;
    }

    /**
     * Sets the value of the typeOfRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeOfRequestType }
     *     
     */
    public void setTypeOfRequest(TypeOfRequestType value) {
        this.typeOfRequest = value;
    }

    /**
     * Gets the value of the requestSubject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestSubject() {
        return requestSubject;
    }

    /**
     * Sets the value of the requestSubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestSubject(String value) {
        this.requestSubject = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * 
     * 
     */
    public List<Element> getAny() {
        if (any == null) {
            any = new ArrayList<Element>();
        }
        return this.any;
    }

    /**
     * Gets the value of the requestText property.
     * 
     * @return
     *     possible object is
     *     {@link FreeTextType }
     *     
     */
    public FreeTextType getRequestText() {
        return requestText;
    }

    /**
     * Sets the value of the requestText property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeTextType }
     *     
     */
    public void setRequestText(FreeTextType value) {
        this.requestText = value;
    }

}
