//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.requests;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TypeOfRequestType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TypeOfRequestType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Request for Information"/>
 *     &lt;enumeration value="Request for Clarification"/>
 *     &lt;enumeration value="Request for Advice"/>
 *     &lt;enumeration value="Request for Assistance"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TypeOfRequestType")
@XmlEnum
public enum TypeOfRequestType {

    @XmlEnumValue("Request for Information")
    REQUEST_FOR_INFORMATION("Request for Information"),
    @XmlEnumValue("Request for Clarification")
    REQUEST_FOR_CLARIFICATION("Request for Clarification"),
    @XmlEnumValue("Request for Advice")
    REQUEST_FOR_ADVICE("Request for Advice"),
    @XmlEnumValue("Request for Assistance")
    REQUEST_FOR_ASSISTANCE("Request for Assistance");
    private final String value;

    TypeOfRequestType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeOfRequestType fromValue(String v) {
        for (TypeOfRequestType c: TypeOfRequestType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
