//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.locations;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.iaea._2012.irix.format.locations package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LocationOffset_QNAME = new QName("http://www.iaea.org/2012/IRIX/Format/Locations", "LocationOffset");
    private final static QName _Locations_QNAME = new QName("http://www.iaea.org/2012/IRIX/Format/Locations", "Locations");
    private final static QName _Location_QNAME = new QName("http://www.iaea.org/2012/IRIX/Format/Locations", "Location");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.iaea._2012.irix.format.locations
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LocationsType }
     * 
     */
    public LocationsType createLocationsType() {
        return new LocationsType();
    }

    /**
     * Create an instance of {@link LocationOrLocationRefType }
     * 
     */
    public LocationOrLocationRefType createLocationOrLocationRefType() {
        return new LocationOrLocationRefType();
    }

    /**
     * Create an instance of {@link LocationOffsetType }
     * 
     */
    public LocationOffsetType createLocationOffsetType() {
        return new LocationOffsetType();
    }

    /**
     * Create an instance of {@link LocationWithIdType }
     * 
     */
    public LocationWithIdType createLocationWithIdType() {
        return new LocationWithIdType();
    }

    /**
     * Create an instance of {@link LocationType }
     * 
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link GeographicCoordinatesType }
     * 
     */
    public GeographicCoordinatesType createGeographicCoordinatesType() {
        return new GeographicCoordinatesType();
    }

    /**
     * Create an instance of {@link HeightType }
     * 
     */
    public HeightType createHeightType() {
        return new HeightType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationOffsetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iaea.org/2012/IRIX/Format/Locations", name = "LocationOffset")
    public JAXBElement<LocationOffsetType> createLocationOffset(LocationOffsetType value) {
        return new JAXBElement<LocationOffsetType>(_LocationOffset_QNAME, LocationOffsetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iaea.org/2012/IRIX/Format/Locations", name = "Locations")
    public JAXBElement<LocationsType> createLocations(LocationsType value) {
        return new JAXBElement<LocationsType>(_Locations_QNAME, LocationsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationOrLocationRefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iaea.org/2012/IRIX/Format/Locations", name = "Location")
    public JAXBElement<LocationOrLocationRefType> createLocation(LocationOrLocationRefType value) {
        return new JAXBElement<LocationOrLocationRefType>(_Location_QNAME, LocationOrLocationRefType.class, null, value);
    }

}
