//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.consequenceinformation;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CasualtyTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CasualtyTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Exposed"/>
 *     &lt;enumeration value="Hospitalised"/>
 *     &lt;enumeration value="Wounded"/>
 *     &lt;enumeration value="Dead"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CasualtyTypeType")
@XmlEnum
public enum CasualtyTypeType {

    @XmlEnumValue("Exposed")
    EXPOSED("Exposed"),
    @XmlEnumValue("Hospitalised")
    HOSPITALISED("Hospitalised"),
    @XmlEnumValue("Wounded")
    WOUNDED("Wounded"),
    @XmlEnumValue("Dead")
    DEAD("Dead");
    private final String value;

    CasualtyTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CasualtyTypeType fromValue(String v) {
        for (CasualtyTypeType c: CasualtyTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
