//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.consequenceinformation;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CasualtiesGroupType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CasualtiesGroupType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Public"/>
 *     &lt;enumeration value="Emergency Services"/>
 *     &lt;enumeration value="Unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CasualtiesGroupType")
@XmlEnum
public enum CasualtiesGroupType {

    @XmlEnumValue("Public")
    PUBLIC("Public"),
    @XmlEnumValue("Emergency Services")
    EMERGENCY_SERVICES("Emergency Services"),
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown");
    private final String value;

    CasualtiesGroupType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CasualtiesGroupType fromValue(String v) {
        for (CasualtiesGroupType c: CasualtiesGroupType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
