//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.consequenceinformation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.iaea._2012.irix.format.base.FreeTextType;
import org.iaea._2012.irix.format.base.InformationBlock;


/**
 * <p>Java class for ConsequencesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConsequencesType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iaea.org/2012/IRIX/Format/Base}InformationBlock">
 *       &lt;sequence>
 *         &lt;element name="HealthIssues" type="{http://www.iaea.org/2012/IRIX/Format/Base}FreeTextType" minOccurs="0"/>
 *         &lt;element name="EnvironmentalIssues" type="{http://www.iaea.org/2012/IRIX/Format/Base}FreeTextType" minOccurs="0"/>
 *         &lt;element name="FoodstuffIssues" type="{http://www.iaea.org/2012/IRIX/Format/Base}FreeTextType" minOccurs="0"/>
 *         &lt;element name="OtherIssues" type="{http://www.iaea.org/2012/IRIX/Format/Base}FreeTextType" minOccurs="0"/>
 *         &lt;element name="AreasAffected" type="{http://www.iaea.org/2012/IRIX/Format/ConsequenceInformation}AreasAffectedType" minOccurs="0"/>
 *         &lt;element name="NumbersOfCasualties" type="{http://www.iaea.org/2012/IRIX/Format/ConsequenceInformation}NumbersOfCasualtiesType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConsequencesType", propOrder = {
    "healthIssues",
    "environmentalIssues",
    "foodstuffIssues",
    "otherIssues",
    "areasAffected",
    "numbersOfCasualties"
})
public class ConsequencesType
    extends InformationBlock
{

    @XmlElement(name = "HealthIssues")
    protected FreeTextType healthIssues;
    @XmlElement(name = "EnvironmentalIssues")
    protected FreeTextType environmentalIssues;
    @XmlElement(name = "FoodstuffIssues")
    protected FreeTextType foodstuffIssues;
    @XmlElement(name = "OtherIssues")
    protected FreeTextType otherIssues;
    @XmlElement(name = "AreasAffected")
    protected AreasAffectedType areasAffected;
    @XmlElement(name = "NumbersOfCasualties")
    protected NumbersOfCasualtiesType numbersOfCasualties;

    /**
     * Gets the value of the healthIssues property.
     * 
     * @return
     *     possible object is
     *     {@link FreeTextType }
     *     
     */
    public FreeTextType getHealthIssues() {
        return healthIssues;
    }

    /**
     * Sets the value of the healthIssues property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeTextType }
     *     
     */
    public void setHealthIssues(FreeTextType value) {
        this.healthIssues = value;
    }

    /**
     * Gets the value of the environmentalIssues property.
     * 
     * @return
     *     possible object is
     *     {@link FreeTextType }
     *     
     */
    public FreeTextType getEnvironmentalIssues() {
        return environmentalIssues;
    }

    /**
     * Sets the value of the environmentalIssues property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeTextType }
     *     
     */
    public void setEnvironmentalIssues(FreeTextType value) {
        this.environmentalIssues = value;
    }

    /**
     * Gets the value of the foodstuffIssues property.
     * 
     * @return
     *     possible object is
     *     {@link FreeTextType }
     *     
     */
    public FreeTextType getFoodstuffIssues() {
        return foodstuffIssues;
    }

    /**
     * Sets the value of the foodstuffIssues property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeTextType }
     *     
     */
    public void setFoodstuffIssues(FreeTextType value) {
        this.foodstuffIssues = value;
    }

    /**
     * Gets the value of the otherIssues property.
     * 
     * @return
     *     possible object is
     *     {@link FreeTextType }
     *     
     */
    public FreeTextType getOtherIssues() {
        return otherIssues;
    }

    /**
     * Sets the value of the otherIssues property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeTextType }
     *     
     */
    public void setOtherIssues(FreeTextType value) {
        this.otherIssues = value;
    }

    /**
     * Gets the value of the areasAffected property.
     * 
     * @return
     *     possible object is
     *     {@link AreasAffectedType }
     *     
     */
    public AreasAffectedType getAreasAffected() {
        return areasAffected;
    }

    /**
     * Sets the value of the areasAffected property.
     * 
     * @param value
     *     allowed object is
     *     {@link AreasAffectedType }
     *     
     */
    public void setAreasAffected(AreasAffectedType value) {
        this.areasAffected = value;
    }

    /**
     * Gets the value of the numbersOfCasualties property.
     * 
     * @return
     *     possible object is
     *     {@link NumbersOfCasualtiesType }
     *     
     */
    public NumbersOfCasualtiesType getNumbersOfCasualties() {
        return numbersOfCasualties;
    }

    /**
     * Sets the value of the numbersOfCasualties property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumbersOfCasualtiesType }
     *     
     */
    public void setNumbersOfCasualties(NumbersOfCasualtiesType value) {
        this.numbersOfCasualties = value;
    }

}
