//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.consequenceinformation;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for NumberOfCasualtiesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NumberOfCasualtiesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="CasualtyType" type="{http://www.iaea.org/2012/IRIX/Format/ConsequenceInformation}CasualtyTypeType"/>
 *           &lt;element name="CasualtyTypeDescription" type="{http://www.iaea.org/2012/IRIX/Format/Base}ShortStringType"/>
 *         &lt;/choice>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="MemberOfGroup" type="{http://www.iaea.org/2012/IRIX/Format/ConsequenceInformation}CasualtiesGroupType"/>
 *           &lt;element name="MemberOfGroupDescription" type="{http://www.iaea.org/2012/IRIX/Format/Base}ShortStringType"/>
 *         &lt;/choice>
 *         &lt;element name="Number" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="MethodOfDetermination" type="{http://www.iaea.org/2012/IRIX/Format/ConsequenceInformation}CasualtiesMethodOfDeterminationType"/>
 *           &lt;element name="MethodOfDeterminationDescription" type="{http://www.iaea.org/2012/IRIX/Format/Base}ShortStringType" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NumberOfCasualtiesType", propOrder = {
    "casualtyType",
    "casualtyTypeDescription",
    "memberOfGroup",
    "memberOfGroupDescription",
    "number",
    "methodOfDetermination",
    "methodOfDeterminationDescription"
})
public class NumberOfCasualtiesType {

    @XmlElement(name = "CasualtyType")
    protected CasualtyTypeType casualtyType;
    @XmlElement(name = "CasualtyTypeDescription")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String casualtyTypeDescription;
    @XmlElement(name = "MemberOfGroup")
    protected CasualtiesGroupType memberOfGroup;
    @XmlElement(name = "MemberOfGroupDescription")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String memberOfGroupDescription;
    @XmlElement(name = "Number", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger number;
    @XmlElement(name = "MethodOfDetermination")
    protected CasualtiesMethodOfDeterminationType methodOfDetermination;
    @XmlElement(name = "MethodOfDeterminationDescription")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String methodOfDeterminationDescription;

    /**
     * Gets the value of the casualtyType property.
     * 
     * @return
     *     possible object is
     *     {@link CasualtyTypeType }
     *     
     */
    public CasualtyTypeType getCasualtyType() {
        return casualtyType;
    }

    /**
     * Sets the value of the casualtyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CasualtyTypeType }
     *     
     */
    public void setCasualtyType(CasualtyTypeType value) {
        this.casualtyType = value;
    }

    /**
     * Gets the value of the casualtyTypeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCasualtyTypeDescription() {
        return casualtyTypeDescription;
    }

    /**
     * Sets the value of the casualtyTypeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCasualtyTypeDescription(String value) {
        this.casualtyTypeDescription = value;
    }

    /**
     * Gets the value of the memberOfGroup property.
     * 
     * @return
     *     possible object is
     *     {@link CasualtiesGroupType }
     *     
     */
    public CasualtiesGroupType getMemberOfGroup() {
        return memberOfGroup;
    }

    /**
     * Sets the value of the memberOfGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link CasualtiesGroupType }
     *     
     */
    public void setMemberOfGroup(CasualtiesGroupType value) {
        this.memberOfGroup = value;
    }

    /**
     * Gets the value of the memberOfGroupDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberOfGroupDescription() {
        return memberOfGroupDescription;
    }

    /**
     * Sets the value of the memberOfGroupDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberOfGroupDescription(String value) {
        this.memberOfGroupDescription = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumber(BigInteger value) {
        this.number = value;
    }

    /**
     * Gets the value of the methodOfDetermination property.
     * 
     * @return
     *     possible object is
     *     {@link CasualtiesMethodOfDeterminationType }
     *     
     */
    public CasualtiesMethodOfDeterminationType getMethodOfDetermination() {
        return methodOfDetermination;
    }

    /**
     * Sets the value of the methodOfDetermination property.
     * 
     * @param value
     *     allowed object is
     *     {@link CasualtiesMethodOfDeterminationType }
     *     
     */
    public void setMethodOfDetermination(CasualtiesMethodOfDeterminationType value) {
        this.methodOfDetermination = value;
    }

    /**
     * Gets the value of the methodOfDeterminationDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethodOfDeterminationDescription() {
        return methodOfDeterminationDescription;
    }

    /**
     * Sets the value of the methodOfDeterminationDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethodOfDeterminationDescription(String value) {
        this.methodOfDeterminationDescription = value;
    }

}
