sudo: true
dist: trusty
cache:
  directories:
    - "$HOME/.m2"
language: java
before_install:
  - rm ~/.m2/settings.xml
  - pwd
  - cd .. && ls
  - git clone https://github.com/OpenBfS/dokpool-javaclient.git
  - git clone https://github.com/OpenBfS/irix-broker.git
  - cd dokpool-javaclient
  - mvn compile package install
  - cd ../irix-broker
  - mvn compile package install
  - cd ../irix-webservice
script:
  - mvn clean compile package install
notifications:
  email:
    on_success: never
    on_failure: never
jdk:
- openjdk7
- oraclejdk8
- openjdk8

