sudo: true
dist: trusty
cache:
  directories:
    - "$HOME/.m2"
language: java
before_install:
  - rm ~/.m2/settings.xml
  - pwd
  - cd .. && git clone https://github.com/OpenBfS/dokpool-javaclient.git && git clone https://github.com/OpenBfS/irix-broker.git && ls
  - ls && cd dokpool-javaclient && ls && mvn clean compile package install && cd .. && ls
  - ls && cd irix-broker && ls && mvn clean compile package install && cd .. && ls
  - ls && cd ../irix-webservice
script:
  - mvn clean compile package install
notifications:
  email:
    on_success: never
    on_failure: never
jdk:
- openjdk7
- oraclejdk8
- openjdk8

