//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.measurements;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ApparatusTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ApparatusTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Alpha - ZnS Scintillator"/>
 *     &lt;enumeration value="Alpha - Track Etching"/>
 *     &lt;enumeration value="Alpha - Solid State Detector"/>
 *     &lt;enumeration value="Alpha - Unspecified"/>
 *     &lt;enumeration value="Beta - Proportional Counter"/>
 *     &lt;enumeration value="Beta - Geiger Muller Counter"/>
 *     &lt;enumeration value="Beta - Plastic Scintillator"/>
 *     &lt;enumeration value="Beta - Liquid Scintillator"/>
 *     &lt;enumeration value="Beta - Solid State Detector"/>
 *     &lt;enumeration value="Beta - Unspecified"/>
 *     &lt;enumeration value="Beta and Alpha - Plastic and ZnS Scintillators, Combination"/>
 *     &lt;enumeration value="Beta and Gamma - Unspecified"/>
 *     &lt;enumeration value="Gamma - TLD"/>
 *     &lt;enumeration value="Gamma - Ionisation Chamber"/>
 *     &lt;enumeration value="Gamma - NaI Detector"/>
 *     &lt;enumeration value="Gamma - Solid State Detector"/>
 *     &lt;enumeration value="Gamma - Unspecified"/>
 *     &lt;enumeration value="Atomic Absorption"/>
 *     &lt;enumeration value="Beta-Geiger Muller or Scintillator"/>
 *     &lt;enumeration value="Gamma Spectrometry Scintillator"/>
 *     &lt;enumeration value="Beta Counting Scintillator"/>
 *     &lt;enumeration value="Alpha Counting"/>
 *     &lt;enumeration value="Gamma-Thermoluminescent Detector"/>
 *     &lt;enumeration value="Alpha Spectrometry"/>
 *     &lt;enumeration value="Gamma Geiger Muller Tube"/>
 *     &lt;enumeration value="Unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ApparatusTypeType")
@XmlEnum
public enum ApparatusTypeType {

    @XmlEnumValue("Alpha - ZnS Scintillator")
    ALPHA_ZN_S_SCINTILLATOR("Alpha - ZnS Scintillator"),
    @XmlEnumValue("Alpha - Track Etching")
    ALPHA_TRACK_ETCHING("Alpha - Track Etching"),
    @XmlEnumValue("Alpha - Solid State Detector")
    ALPHA_SOLID_STATE_DETECTOR("Alpha - Solid State Detector"),
    @XmlEnumValue("Alpha - Unspecified")
    ALPHA_UNSPECIFIED("Alpha - Unspecified"),
    @XmlEnumValue("Beta - Proportional Counter")
    BETA_PROPORTIONAL_COUNTER("Beta - Proportional Counter"),
    @XmlEnumValue("Beta - Geiger Muller Counter")
    BETA_GEIGER_MULLER_COUNTER("Beta - Geiger Muller Counter"),
    @XmlEnumValue("Beta - Plastic Scintillator")
    BETA_PLASTIC_SCINTILLATOR("Beta - Plastic Scintillator"),
    @XmlEnumValue("Beta - Liquid Scintillator")
    BETA_LIQUID_SCINTILLATOR("Beta - Liquid Scintillator"),
    @XmlEnumValue("Beta - Solid State Detector")
    BETA_SOLID_STATE_DETECTOR("Beta - Solid State Detector"),
    @XmlEnumValue("Beta - Unspecified")
    BETA_UNSPECIFIED("Beta - Unspecified"),
    @XmlEnumValue("Beta and Alpha - Plastic and ZnS Scintillators, Combination")
    BETA_AND_ALPHA_PLASTIC_AND_ZN_S_SCINTILLATORS_COMBINATION("Beta and Alpha - Plastic and ZnS Scintillators, Combination"),
    @XmlEnumValue("Beta and Gamma - Unspecified")
    BETA_AND_GAMMA_UNSPECIFIED("Beta and Gamma - Unspecified"),
    @XmlEnumValue("Gamma - TLD")
    GAMMA_TLD("Gamma - TLD"),
    @XmlEnumValue("Gamma - Ionisation Chamber")
    GAMMA_IONISATION_CHAMBER("Gamma - Ionisation Chamber"),
    @XmlEnumValue("Gamma - NaI Detector")
    GAMMA_NA_I_DETECTOR("Gamma - NaI Detector"),
    @XmlEnumValue("Gamma - Solid State Detector")
    GAMMA_SOLID_STATE_DETECTOR("Gamma - Solid State Detector"),
    @XmlEnumValue("Gamma - Unspecified")
    GAMMA_UNSPECIFIED("Gamma - Unspecified"),
    @XmlEnumValue("Atomic Absorption")
    ATOMIC_ABSORPTION("Atomic Absorption"),
    @XmlEnumValue("Beta-Geiger Muller or Scintillator")
    BETA_GEIGER_MULLER_OR_SCINTILLATOR("Beta-Geiger Muller or Scintillator"),
    @XmlEnumValue("Gamma Spectrometry Scintillator")
    GAMMA_SPECTROMETRY_SCINTILLATOR("Gamma Spectrometry Scintillator"),
    @XmlEnumValue("Beta Counting Scintillator")
    BETA_COUNTING_SCINTILLATOR("Beta Counting Scintillator"),
    @XmlEnumValue("Alpha Counting")
    ALPHA_COUNTING("Alpha Counting"),
    @XmlEnumValue("Gamma-Thermoluminescent Detector")
    GAMMA_THERMOLUMINESCENT_DETECTOR("Gamma-Thermoluminescent Detector"),
    @XmlEnumValue("Alpha Spectrometry")
    ALPHA_SPECTROMETRY("Alpha Spectrometry"),
    @XmlEnumValue("Gamma Geiger Muller Tube")
    GAMMA_GEIGER_MULLER_TUBE("Gamma Geiger Muller Tube"),
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown");
    private final String value;

    ApparatusTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ApparatusTypeType fromValue(String v) {
        for (ApparatusTypeType c: ApparatusTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
