//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.measurements;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DoseRateTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DoseRateTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Gamma"/>
 *     &lt;enumeration value="Beta"/>
 *     &lt;enumeration value="Beta-Gamma"/>
 *     &lt;enumeration value="Neutron"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DoseRateTypeType")
@XmlEnum
public enum DoseRateTypeType {

    @XmlEnumValue("Gamma")
    GAMMA("Gamma"),
    @XmlEnumValue("Beta")
    BETA("Beta"),
    @XmlEnumValue("Beta-Gamma")
    BETA_GAMMA("Beta-Gamma"),
    @XmlEnumValue("Neutron")
    NEUTRON("Neutron");
    private final String value;

    DoseRateTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DoseRateTypeType fromValue(String v) {
        for (DoseRateTypeType c: DoseRateTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
