//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.measurements;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.iaea._2012.irix.format.base.FreeTextType;


/**
 * <p>Java class for DoseRateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DoseRateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DoseRateType" type="{http://www.iaea.org/2012/IRIX/Format/Measurements}DoseRateTypeType"/>
 *         &lt;element name="MeasuringPeriod" type="{http://www.iaea.org/2012/IRIX/Format/Measurements}MeasuringPeriodType"/>
 *         &lt;group ref="{http://www.iaea.org/2012/IRIX/Format/Measurements}ApparatusTypeGroup" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.iaea.org/2012/IRIX/Format/Base}FreeTextType" minOccurs="0"/>
 *         &lt;element name="Measurements" type="{http://www.iaea.org/2012/IRIX/Format/Measurements}DoseRateMeasurementsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DoseRateType", propOrder = {
    "doseRateType",
    "measuringPeriod",
    "apparatusType",
    "apparatusTypeDescription",
    "description",
    "measurements"
})
public class DoseRateType {

    @XmlElement(name = "DoseRateType", required = true)
    protected DoseRateTypeType doseRateType;
    @XmlElement(name = "MeasuringPeriod", required = true)
    protected MeasuringPeriodType measuringPeriod;
    @XmlElement(name = "ApparatusType")
    protected ApparatusTypeType apparatusType;
    @XmlElement(name = "ApparatusTypeDescription")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String apparatusTypeDescription;
    @XmlElement(name = "Description")
    protected FreeTextType description;
    @XmlElement(name = "Measurements", required = true)
    protected DoseRateMeasurementsType measurements;

    /**
     * Gets the value of the doseRateType property.
     * 
     * @return
     *     possible object is
     *     {@link DoseRateTypeType }
     *     
     */
    public DoseRateTypeType getDoseRateType() {
        return doseRateType;
    }

    /**
     * Sets the value of the doseRateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoseRateTypeType }
     *     
     */
    public void setDoseRateType(DoseRateTypeType value) {
        this.doseRateType = value;
    }

    /**
     * Gets the value of the measuringPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link MeasuringPeriodType }
     *     
     */
    public MeasuringPeriodType getMeasuringPeriod() {
        return measuringPeriod;
    }

    /**
     * Sets the value of the measuringPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasuringPeriodType }
     *     
     */
    public void setMeasuringPeriod(MeasuringPeriodType value) {
        this.measuringPeriod = value;
    }

    /**
     * Gets the value of the apparatusType property.
     * 
     * @return
     *     possible object is
     *     {@link ApparatusTypeType }
     *     
     */
    public ApparatusTypeType getApparatusType() {
        return apparatusType;
    }

    /**
     * Sets the value of the apparatusType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApparatusTypeType }
     *     
     */
    public void setApparatusType(ApparatusTypeType value) {
        this.apparatusType = value;
    }

    /**
     * Gets the value of the apparatusTypeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApparatusTypeDescription() {
        return apparatusTypeDescription;
    }

    /**
     * Sets the value of the apparatusTypeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApparatusTypeDescription(String value) {
        this.apparatusTypeDescription = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link FreeTextType }
     *     
     */
    public FreeTextType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeTextType }
     *     
     */
    public void setDescription(FreeTextType value) {
        this.description = value;
    }

    /**
     * Gets the value of the measurements property.
     * 
     * @return
     *     possible object is
     *     {@link DoseRateMeasurementsType }
     *     
     */
    public DoseRateMeasurementsType getMeasurements() {
        return measurements;
    }

    /**
     * Sets the value of the measurements property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoseRateMeasurementsType }
     *     
     */
    public void setMeasurements(DoseRateMeasurementsType value) {
        this.measurements = value;
    }

}
