//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.measurements;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;
import org.iaea._2012.irix.format.base.FreeTextType;
import org.iaea._2012.irix.format.locations.LocationOffsetType;
import org.iaea._2012.irix.format.locations.LocationOrLocationRefType;


/**
 * <p>Java class for DoseRateMeasurementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DoseRateMeasurementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.iaea.org/2012/IRIX/Format/Locations}Location"/>
 *         &lt;element ref="{http://www.iaea.org/2012/IRIX/Format/Locations}LocationOffset" minOccurs="0"/>
 *         &lt;group ref="{http://www.iaea.org/2012/IRIX/Format/Measurements}MeasurementGroup"/>
 *         &lt;group ref="{http://www.iaea.org/2012/IRIX/Format/Measurements}ValidationElementsGroup" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.iaea.org/2012/IRIX/Format/Base}FreeTextType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DoseRateMeasurementType", propOrder = {
    "location",
    "locationOffset",
    "value",
    "uncertainty",
    "timebase",
    "background",
    "validated",
    "description"
})
public class DoseRateMeasurementType {

    @XmlElement(name = "Location", namespace = "http://www.iaea.org/2012/IRIX/Format/Locations", required = true)
    protected LocationOrLocationRefType location;
    @XmlElement(name = "LocationOffset", namespace = "http://www.iaea.org/2012/IRIX/Format/Locations")
    protected LocationOffsetType locationOffset;
    @XmlElement(name = "Value", required = true)
    protected MeasurementValueType value;
    @XmlElement(name = "Uncertainty")
    protected UncertaintyType uncertainty;
    @XmlElement(name = "Timebase")
    protected Duration timebase;
    @XmlElement(name = "Background")
    protected BackgroundType background;
    @XmlElement(name = "Validated")
    protected ValidatedType validated;
    @XmlElement(name = "Description")
    protected FreeTextType description;

    /**
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;html:p xmlns:html="http://www.w3.org/1999/xhtml" xmlns:base="http://www.iaea.org/2012/IRIX/Format/Base" xmlns:loc="http://www.iaea.org/2012/IRIX/Format/Locations" xmlns:meas="http://www.iaea.org/2012/IRIX/Format/Measurements" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;
     * 							Location of measurement, or reference
     * 							location from which distance and direction (offset) to 
     * 							this location is provided.
     * 						&lt;/html:p&gt;
     * </pre>
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;html:p xmlns:html="http://www.w3.org/1999/xhtml" xmlns:base="http://www.iaea.org/2012/IRIX/Format/Base" xmlns:loc="http://www.iaea.org/2012/IRIX/Format/Locations" xmlns:meas="http://www.iaea.org/2012/IRIX/Format/Measurements" xmlns:xsd="http://www.w3.org/2001/XMLSchema" class="note"&gt;
     * 							For the structure of this element, see Locations section.
     * 						&lt;/html:p&gt;
     * </pre>
     * 
     * 					
     * 
     * @return
     *     possible object is
     *     {@link LocationOrLocationRefType }
     *     
     */
    public LocationOrLocationRefType getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationOrLocationRefType }
     *     
     */
    public void setLocation(LocationOrLocationRefType value) {
        this.location = value;
    }

    /**
     * 
     * 						Location of measurement, given by 
     * 						distance and direction (offset) from reference location.
     * 					
     * 
     * @return
     *     possible object is
     *     {@link LocationOffsetType }
     *     
     */
    public LocationOffsetType getLocationOffset() {
        return locationOffset;
    }

    /**
     * Sets the value of the locationOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationOffsetType }
     *     
     */
    public void setLocationOffset(LocationOffsetType value) {
        this.locationOffset = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link MeasurementValueType }
     *     
     */
    public MeasurementValueType getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasurementValueType }
     *     
     */
    public void setValue(MeasurementValueType value) {
        this.value = value;
    }

    /**
     * Gets the value of the uncertainty property.
     * 
     * @return
     *     possible object is
     *     {@link UncertaintyType }
     *     
     */
    public UncertaintyType getUncertainty() {
        return uncertainty;
    }

    /**
     * Sets the value of the uncertainty property.
     * 
     * @param value
     *     allowed object is
     *     {@link UncertaintyType }
     *     
     */
    public void setUncertainty(UncertaintyType value) {
        this.uncertainty = value;
    }

    /**
     * Gets the value of the timebase property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getTimebase() {
        return timebase;
    }

    /**
     * Sets the value of the timebase property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setTimebase(Duration value) {
        this.timebase = value;
    }

    /**
     * Gets the value of the background property.
     * 
     * @return
     *     possible object is
     *     {@link BackgroundType }
     *     
     */
    public BackgroundType getBackground() {
        return background;
    }

    /**
     * Sets the value of the background property.
     * 
     * @param value
     *     allowed object is
     *     {@link BackgroundType }
     *     
     */
    public void setBackground(BackgroundType value) {
        this.background = value;
    }

    /**
     * Gets the value of the validated property.
     * 
     * @return
     *     possible object is
     *     {@link ValidatedType }
     *     
     */
    public ValidatedType getValidated() {
        return validated;
    }

    /**
     * Sets the value of the validated property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidatedType }
     *     
     */
    public void setValidated(ValidatedType value) {
        this.validated = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link FreeTextType }
     *     
     */
    public FreeTextType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeTextType }
     *     
     */
    public void setDescription(FreeTextType value) {
        this.description = value;
    }

}
