//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.measurements;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MeasurementValueTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MeasurementValueTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Discrete Single Measurements"/>
 *     &lt;enumeration value="Discrete Sample From Single Source"/>
 *     &lt;enumeration value="Discrete Sample From Bulked Source"/>
 *     &lt;enumeration value="Time Average Discrete Measurements"/>
 *     &lt;enumeration value="Time Average - 1 Week"/>
 *     &lt;enumeration value="Time Average - 1 Month"/>
 *     &lt;enumeration value="Time Average - 2 Months"/>
 *     &lt;enumeration value="Time Average - 3 Months"/>
 *     &lt;enumeration value="Time Average - 6 Months"/>
 *     &lt;enumeration value="Time Average - 1 Year"/>
 *     &lt;enumeration value="Geographical Average Discrete Measurements"/>
 *     &lt;enumeration value="Time and Geographical Average"/>
 *     &lt;enumeration value="Bulked Sample Average"/>
 *     &lt;enumeration value="Centre Point of Quoted Range"/>
 *     &lt;enumeration value="Highest Value"/>
 *     &lt;enumeration value="Lowest Value"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MeasurementValueTypeType")
@XmlEnum
public enum MeasurementValueTypeType {

    @XmlEnumValue("Discrete Single Measurements")
    DISCRETE_SINGLE_MEASUREMENTS("Discrete Single Measurements"),
    @XmlEnumValue("Discrete Sample From Single Source")
    DISCRETE_SAMPLE_FROM_SINGLE_SOURCE("Discrete Sample From Single Source"),
    @XmlEnumValue("Discrete Sample From Bulked Source")
    DISCRETE_SAMPLE_FROM_BULKED_SOURCE("Discrete Sample From Bulked Source"),
    @XmlEnumValue("Time Average Discrete Measurements")
    TIME_AVERAGE_DISCRETE_MEASUREMENTS("Time Average Discrete Measurements"),
    @XmlEnumValue("Time Average - 1 Week")
    TIME_AVERAGE_1_WEEK("Time Average - 1 Week"),
    @XmlEnumValue("Time Average - 1 Month")
    TIME_AVERAGE_1_MONTH("Time Average - 1 Month"),
    @XmlEnumValue("Time Average - 2 Months")
    TIME_AVERAGE_2_MONTHS("Time Average - 2 Months"),
    @XmlEnumValue("Time Average - 3 Months")
    TIME_AVERAGE_3_MONTHS("Time Average - 3 Months"),
    @XmlEnumValue("Time Average - 6 Months")
    TIME_AVERAGE_6_MONTHS("Time Average - 6 Months"),
    @XmlEnumValue("Time Average - 1 Year")
    TIME_AVERAGE_1_YEAR("Time Average - 1 Year"),
    @XmlEnumValue("Geographical Average Discrete Measurements")
    GEOGRAPHICAL_AVERAGE_DISCRETE_MEASUREMENTS("Geographical Average Discrete Measurements"),
    @XmlEnumValue("Time and Geographical Average")
    TIME_AND_GEOGRAPHICAL_AVERAGE("Time and Geographical Average"),
    @XmlEnumValue("Bulked Sample Average")
    BULKED_SAMPLE_AVERAGE("Bulked Sample Average"),
    @XmlEnumValue("Centre Point of Quoted Range")
    CENTRE_POINT_OF_QUOTED_RANGE("Centre Point of Quoted Range"),
    @XmlEnumValue("Highest Value")
    HIGHEST_VALUE("Highest Value"),
    @XmlEnumValue("Lowest Value")
    LOWEST_VALUE("Lowest Value");
    private final String value;

    MeasurementValueTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MeasurementValueTypeType fromValue(String v) {
        for (MeasurementValueTypeType c: MeasurementValueTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
