//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.measurements;

import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;
import org.iaea._2012.irix.format.base.FreeTextType;


/**
 * <p>Java class for SampleMeasurementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SampleMeasurementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.iaea.org/2012/IRIX/Format/Measurements}NuclideInfo"/>
 *         &lt;group ref="{http://www.iaea.org/2012/IRIX/Format/Measurements}MeasurementGroup"/>
 *         &lt;element name="MeasuringPeriod" type="{http://www.iaea.org/2012/IRIX/Format/Measurements}MeasuringPeriodType" minOccurs="0"/>
 *         &lt;element name="ReferenceDateAndTime" type="{http://www.iaea.org/2012/IRIX/Format/Base}DateTimeType" minOccurs="0"/>
 *         &lt;group ref="{http://www.iaea.org/2012/IRIX/Format/Measurements}ApparatusTypeGroup" minOccurs="0"/>
 *         &lt;group ref="{http://www.iaea.org/2012/IRIX/Format/Measurements}ValidationElementsGroup" minOccurs="0"/>
 *         &lt;element name="Laboratory" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.iaea.org/2012/IRIX/Format/Base}FreeTextType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SampleMeasurementType", propOrder = {
    "nuclideInfo",
    "value",
    "uncertainty",
    "timebase",
    "background",
    "measuringPeriod",
    "referenceDateAndTime",
    "apparatusType",
    "apparatusTypeDescription",
    "validated",
    "laboratory",
    "description"
})
public class SampleMeasurementType {

    @XmlElementRef(name = "NuclideInfo", namespace = "http://www.iaea.org/2012/IRIX/Format/Measurements", type = JAXBElement.class)
    protected JAXBElement<?> nuclideInfo;
    @XmlElement(name = "Value", required = true)
    protected MeasurementValueType value;
    @XmlElement(name = "Uncertainty")
    protected UncertaintyType uncertainty;
    @XmlElement(name = "Timebase")
    protected Duration timebase;
    @XmlElement(name = "Background")
    protected BackgroundType background;
    @XmlElement(name = "MeasuringPeriod")
    protected MeasuringPeriodType measuringPeriod;
    @XmlElement(name = "ReferenceDateAndTime")
    protected XMLGregorianCalendar referenceDateAndTime;
    @XmlElement(name = "ApparatusType")
    protected ApparatusTypeType apparatusType;
    @XmlElement(name = "ApparatusTypeDescription")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String apparatusTypeDescription;
    @XmlElement(name = "Validated")
    protected ValidatedType validated;
    @XmlElement(name = "Laboratory")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String laboratory;
    @XmlElement(name = "Description")
    protected FreeTextType description;

    /**
     * 
     * 						The nuclide/s, or combination of nuclides, measured.  
     * 					
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link List }{@code <}{@link String }{@code >}{@code >}
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     {@link JAXBElement }{@code <}{@link NuclideCombinationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<?> getNuclideInfo() {
        return nuclideInfo;
    }

    /**
     * Sets the value of the nuclideInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link List }{@code <}{@link String }{@code >}{@code >}
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     {@link JAXBElement }{@code <}{@link NuclideCombinationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setNuclideInfo(JAXBElement<?> value) {
        this.nuclideInfo = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link MeasurementValueType }
     *     
     */
    public MeasurementValueType getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasurementValueType }
     *     
     */
    public void setValue(MeasurementValueType value) {
        this.value = value;
    }

    /**
     * Gets the value of the uncertainty property.
     * 
     * @return
     *     possible object is
     *     {@link UncertaintyType }
     *     
     */
    public UncertaintyType getUncertainty() {
        return uncertainty;
    }

    /**
     * Sets the value of the uncertainty property.
     * 
     * @param value
     *     allowed object is
     *     {@link UncertaintyType }
     *     
     */
    public void setUncertainty(UncertaintyType value) {
        this.uncertainty = value;
    }

    /**
     * Gets the value of the timebase property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getTimebase() {
        return timebase;
    }

    /**
     * Sets the value of the timebase property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setTimebase(Duration value) {
        this.timebase = value;
    }

    /**
     * Gets the value of the background property.
     * 
     * @return
     *     possible object is
     *     {@link BackgroundType }
     *     
     */
    public BackgroundType getBackground() {
        return background;
    }

    /**
     * Sets the value of the background property.
     * 
     * @param value
     *     allowed object is
     *     {@link BackgroundType }
     *     
     */
    public void setBackground(BackgroundType value) {
        this.background = value;
    }

    /**
     * Gets the value of the measuringPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link MeasuringPeriodType }
     *     
     */
    public MeasuringPeriodType getMeasuringPeriod() {
        return measuringPeriod;
    }

    /**
     * Sets the value of the measuringPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasuringPeriodType }
     *     
     */
    public void setMeasuringPeriod(MeasuringPeriodType value) {
        this.measuringPeriod = value;
    }

    /**
     * Gets the value of the referenceDateAndTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReferenceDateAndTime() {
        return referenceDateAndTime;
    }

    /**
     * Sets the value of the referenceDateAndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReferenceDateAndTime(XMLGregorianCalendar value) {
        this.referenceDateAndTime = value;
    }

    /**
     * Gets the value of the apparatusType property.
     * 
     * @return
     *     possible object is
     *     {@link ApparatusTypeType }
     *     
     */
    public ApparatusTypeType getApparatusType() {
        return apparatusType;
    }

    /**
     * Sets the value of the apparatusType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApparatusTypeType }
     *     
     */
    public void setApparatusType(ApparatusTypeType value) {
        this.apparatusType = value;
    }

    /**
     * Gets the value of the apparatusTypeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApparatusTypeDescription() {
        return apparatusTypeDescription;
    }

    /**
     * Sets the value of the apparatusTypeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApparatusTypeDescription(String value) {
        this.apparatusTypeDescription = value;
    }

    /**
     * Gets the value of the validated property.
     * 
     * @return
     *     possible object is
     *     {@link ValidatedType }
     *     
     */
    public ValidatedType getValidated() {
        return validated;
    }

    /**
     * Sets the value of the validated property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidatedType }
     *     
     */
    public void setValidated(ValidatedType value) {
        this.validated = value;
    }

    /**
     * Gets the value of the laboratory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLaboratory() {
        return laboratory;
    }

    /**
     * Sets the value of the laboratory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLaboratory(String value) {
        this.laboratory = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link FreeTextType }
     *     
     */
    public FreeTextType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeTextType }
     *     
     */
    public void setDescription(FreeTextType value) {
        this.description = value;
    }

}
