//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.measurements;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.iaea._2012.irix.format.base.FreeTextType;
import org.iaea._2012.irix.format.locations.LocationOffsetType;
import org.iaea._2012.irix.format.locations.LocationOrLocationRefType;


/**
 * <p>Java class for SampleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SampleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="SampleType" type="{http://www.iaea.org/2012/IRIX/Format/Measurements}SampleTypeType"/>
 *           &lt;element name="SampleTypeDescription" type="{http://www.iaea.org/2012/IRIX/Format/Base}ShortStringType"/>
 *         &lt;/choice>
 *         &lt;element name="SamplingPeriod" type="{http://www.iaea.org/2012/IRIX/Format/Measurements}SamplingPeriodType"/>
 *         &lt;element ref="{http://www.iaea.org/2012/IRIX/Format/Locations}Location"/>
 *         &lt;element ref="{http://www.iaea.org/2012/IRIX/Format/Locations}LocationOffset" minOccurs="0"/>
 *         &lt;element name="ValueType" type="{http://www.iaea.org/2012/IRIX/Format/Measurements}MeasurementValueTypeType" minOccurs="0"/>
 *         &lt;element name="SamplingDepth" type="{http://www.iaea.org/2012/IRIX/Format/Measurements}SamplingDepthType" minOccurs="0"/>
 *         &lt;element name="SurfaceTypeDescription" type="{http://www.iaea.org/2012/IRIX/Format/Base}ShortStringType" minOccurs="0"/>
 *         &lt;element name="Volume" type="{http://www.iaea.org/2012/IRIX/Format/Measurements}VolumeType" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="SampleTreatment" type="{http://www.iaea.org/2012/IRIX/Format/Measurements}SampleTreatmentType"/>
 *           &lt;element name="SampleTreatmentDescription" type="{http://www.iaea.org/2012/IRIX/Format/Base}ShortStringType"/>
 *         &lt;/choice>
 *         &lt;element name="Description" type="{http://www.iaea.org/2012/IRIX/Format/Base}FreeTextType" minOccurs="0"/>
 *         &lt;element name="Measurements" type="{http://www.iaea.org/2012/IRIX/Format/Measurements}SampleMeasurementsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SampleType", propOrder = {
    "sampleType",
    "sampleTypeDescription",
    "samplingPeriod",
    "location",
    "locationOffset",
    "valueType",
    "samplingDepth",
    "surfaceTypeDescription",
    "volume",
    "sampleTreatment",
    "sampleTreatmentDescription",
    "description",
    "measurements"
})
public class SampleType {

    @XmlElement(name = "SampleType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sampleType;
    @XmlElement(name = "SampleTypeDescription")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sampleTypeDescription;
    @XmlElement(name = "SamplingPeriod", required = true)
    protected SamplingPeriodType samplingPeriod;
    @XmlElement(name = "Location", namespace = "http://www.iaea.org/2012/IRIX/Format/Locations", required = true)
    protected LocationOrLocationRefType location;
    @XmlElement(name = "LocationOffset", namespace = "http://www.iaea.org/2012/IRIX/Format/Locations")
    protected LocationOffsetType locationOffset;
    @XmlElement(name = "ValueType")
    protected MeasurementValueTypeType valueType;
    @XmlElement(name = "SamplingDepth")
    protected SamplingDepthType samplingDepth;
    @XmlElement(name = "SurfaceTypeDescription")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String surfaceTypeDescription;
    @XmlElement(name = "Volume")
    protected VolumeType volume;
    @XmlElement(name = "SampleTreatment")
    protected SampleTreatmentType sampleTreatment;
    @XmlElement(name = "SampleTreatmentDescription")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sampleTreatmentDescription;
    @XmlElement(name = "Description")
    protected FreeTextType description;
    @XmlElement(name = "Measurements", required = true)
    protected SampleMeasurementsType measurements;

    /**
     * Gets the value of the sampleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSampleType() {
        return sampleType;
    }

    /**
     * Sets the value of the sampleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSampleType(String value) {
        this.sampleType = value;
    }

    /**
     * Gets the value of the sampleTypeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSampleTypeDescription() {
        return sampleTypeDescription;
    }

    /**
     * Sets the value of the sampleTypeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSampleTypeDescription(String value) {
        this.sampleTypeDescription = value;
    }

    /**
     * Gets the value of the samplingPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link SamplingPeriodType }
     *     
     */
    public SamplingPeriodType getSamplingPeriod() {
        return samplingPeriod;
    }

    /**
     * Sets the value of the samplingPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamplingPeriodType }
     *     
     */
    public void setSamplingPeriod(SamplingPeriodType value) {
        this.samplingPeriod = value;
    }

    /**
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;html:p xmlns:html="http://www.w3.org/1999/xhtml" xmlns:base="http://www.iaea.org/2012/IRIX/Format/Base" xmlns:loc="http://www.iaea.org/2012/IRIX/Format/Locations" xmlns:meas="http://www.iaea.org/2012/IRIX/Format/Measurements" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;
     * 							Sampling location/area,
     * 							or reference location from which distance and direction (offset) to 
     * 							this location is provided.
     * 						&lt;/html:p&gt;
     * </pre>
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;html:p xmlns:html="http://www.w3.org/1999/xhtml" xmlns:base="http://www.iaea.org/2012/IRIX/Format/Base" xmlns:loc="http://www.iaea.org/2012/IRIX/Format/Locations" xmlns:meas="http://www.iaea.org/2012/IRIX/Format/Measurements" xmlns:xsd="http://www.w3.org/2001/XMLSchema" class="note"&gt;
     * 							For the structure of this element, see Locations section.
     * 						&lt;/html:p&gt;
     * </pre>
     * 
     * 					
     * 
     * @return
     *     possible object is
     *     {@link LocationOrLocationRefType }
     *     
     */
    public LocationOrLocationRefType getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationOrLocationRefType }
     *     
     */
    public void setLocation(LocationOrLocationRefType value) {
        this.location = value;
    }

    /**
     * 
     * 						Sampling location, given by 
     * 						distance and direction (offset) from given reference location.
     * 					
     * 
     * @return
     *     possible object is
     *     {@link LocationOffsetType }
     *     
     */
    public LocationOffsetType getLocationOffset() {
        return locationOffset;
    }

    /**
     * Sets the value of the locationOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationOffsetType }
     *     
     */
    public void setLocationOffset(LocationOffsetType value) {
        this.locationOffset = value;
    }

    /**
     * Gets the value of the valueType property.
     * 
     * @return
     *     possible object is
     *     {@link MeasurementValueTypeType }
     *     
     */
    public MeasurementValueTypeType getValueType() {
        return valueType;
    }

    /**
     * Sets the value of the valueType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasurementValueTypeType }
     *     
     */
    public void setValueType(MeasurementValueTypeType value) {
        this.valueType = value;
    }

    /**
     * Gets the value of the samplingDepth property.
     * 
     * @return
     *     possible object is
     *     {@link SamplingDepthType }
     *     
     */
    public SamplingDepthType getSamplingDepth() {
        return samplingDepth;
    }

    /**
     * Sets the value of the samplingDepth property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamplingDepthType }
     *     
     */
    public void setSamplingDepth(SamplingDepthType value) {
        this.samplingDepth = value;
    }

    /**
     * Gets the value of the surfaceTypeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSurfaceTypeDescription() {
        return surfaceTypeDescription;
    }

    /**
     * Sets the value of the surfaceTypeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurfaceTypeDescription(String value) {
        this.surfaceTypeDescription = value;
    }

    /**
     * Gets the value of the volume property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeType }
     *     
     */
    public VolumeType getVolume() {
        return volume;
    }

    /**
     * Sets the value of the volume property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeType }
     *     
     */
    public void setVolume(VolumeType value) {
        this.volume = value;
    }

    /**
     * Gets the value of the sampleTreatment property.
     * 
     * @return
     *     possible object is
     *     {@link SampleTreatmentType }
     *     
     */
    public SampleTreatmentType getSampleTreatment() {
        return sampleTreatment;
    }

    /**
     * Sets the value of the sampleTreatment property.
     * 
     * @param value
     *     allowed object is
     *     {@link SampleTreatmentType }
     *     
     */
    public void setSampleTreatment(SampleTreatmentType value) {
        this.sampleTreatment = value;
    }

    /**
     * Gets the value of the sampleTreatmentDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSampleTreatmentDescription() {
        return sampleTreatmentDescription;
    }

    /**
     * Sets the value of the sampleTreatmentDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSampleTreatmentDescription(String value) {
        this.sampleTreatmentDescription = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link FreeTextType }
     *     
     */
    public FreeTextType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeTextType }
     *     
     */
    public void setDescription(FreeTextType value) {
        this.description = value;
    }

    /**
     * Gets the value of the measurements property.
     * 
     * @return
     *     possible object is
     *     {@link SampleMeasurementsType }
     *     
     */
    public SampleMeasurementsType getMeasurements() {
        return measurements;
    }

    /**
     * Sets the value of the measurements property.
     * 
     * @param value
     *     allowed object is
     *     {@link SampleMeasurementsType }
     *     
     */
    public void setMeasurements(SampleMeasurementsType value) {
        this.measurements = value;
    }

}
