//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.measurements;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SampleTreatmentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SampleTreatmentType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Carbonisation and Homogenisation"/>
 *     &lt;enumeration value="Drying and Ashing"/>
 *     &lt;enumeration value="Delay of 5 Days"/>
 *     &lt;enumeration value="Delay of 3 Days"/>
 *     &lt;enumeration value="Measurement Immediately After Sampling"/>
 *     &lt;enumeration value="Measurement Within One Week After Sampling"/>
 *     &lt;enumeration value="Gas Chromatographic Separation"/>
 *     &lt;enumeration value="Ion Chromatographic Separation of Nuclides"/>
 *     &lt;enumeration value="(Radio)Chemical Separation of Nuclides"/>
 *     &lt;enumeration value="'On Line' Separation of Nuclides by Ion-Exchange"/>
 *     &lt;enumeration value="Sample Being Deep Frozen"/>
 *     &lt;enumeration value="Oven Dried - Stones Removed"/>
 *     &lt;enumeration value="Liquid Reduced to its Residue by Drying, Evaporation, Calcination"/>
 *     &lt;enumeration value="Suspended Matter Removed by Filtration"/>
 *     &lt;enumeration value="Suspended Matter Selected by Filtration"/>
 *     &lt;enumeration value="Evaporated Dryless"/>
 *     &lt;enumeration value="Homogenisation"/>
 *     &lt;enumeration value="Liquid Reduced to 50% of its Original Volume"/>
 *     &lt;enumeration value="Cleaned and Mixed"/>
 *     &lt;enumeration value="Pulverisation and Homogenisation"/>
 *     &lt;enumeration value="Air Dried if Necessary, Stones Removed"/>
 *     &lt;enumeration value="Sample Washed"/>
 *     &lt;enumeration value="Evaporation + Ashing, Filtering + Ashing"/>
 *     &lt;enumeration value="Dried + Homogenised"/>
 *     &lt;enumeration value="Mixed"/>
 *     &lt;enumeration value="No Treatment"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SampleTreatmentType")
@XmlEnum
public enum SampleTreatmentType {

    @XmlEnumValue("Carbonisation and Homogenisation")
    CARBONISATION_AND_HOMOGENISATION("Carbonisation and Homogenisation"),
    @XmlEnumValue("Drying and Ashing")
    DRYING_AND_ASHING("Drying and Ashing"),
    @XmlEnumValue("Delay of 5 Days")
    DELAY_OF_5_DAYS("Delay of 5 Days"),
    @XmlEnumValue("Delay of 3 Days")
    DELAY_OF_3_DAYS("Delay of 3 Days"),
    @XmlEnumValue("Measurement Immediately After Sampling")
    MEASUREMENT_IMMEDIATELY_AFTER_SAMPLING("Measurement Immediately After Sampling"),
    @XmlEnumValue("Measurement Within One Week After Sampling")
    MEASUREMENT_WITHIN_ONE_WEEK_AFTER_SAMPLING("Measurement Within One Week After Sampling"),
    @XmlEnumValue("Gas Chromatographic Separation")
    GAS_CHROMATOGRAPHIC_SEPARATION("Gas Chromatographic Separation"),
    @XmlEnumValue("Ion Chromatographic Separation of Nuclides")
    ION_CHROMATOGRAPHIC_SEPARATION_OF_NUCLIDES("Ion Chromatographic Separation of Nuclides"),
    @XmlEnumValue("(Radio)Chemical Separation of Nuclides")
    RADIO_CHEMICAL_SEPARATION_OF_NUCLIDES("(Radio)Chemical Separation of Nuclides"),
    @XmlEnumValue("'On Line' Separation of Nuclides by Ion-Exchange")
    ON_LINE_SEPARATION_OF_NUCLIDES_BY_ION_EXCHANGE("'On Line' Separation of Nuclides by Ion-Exchange"),
    @XmlEnumValue("Sample Being Deep Frozen")
    SAMPLE_BEING_DEEP_FROZEN("Sample Being Deep Frozen"),
    @XmlEnumValue("Oven Dried - Stones Removed")
    OVEN_DRIED_STONES_REMOVED("Oven Dried - Stones Removed"),
    @XmlEnumValue("Liquid Reduced to its Residue by Drying, Evaporation, Calcination")
    LIQUID_REDUCED_TO_ITS_RESIDUE_BY_DRYING_EVAPORATION_CALCINATION("Liquid Reduced to its Residue by Drying, Evaporation, Calcination"),
    @XmlEnumValue("Suspended Matter Removed by Filtration")
    SUSPENDED_MATTER_REMOVED_BY_FILTRATION("Suspended Matter Removed by Filtration"),
    @XmlEnumValue("Suspended Matter Selected by Filtration")
    SUSPENDED_MATTER_SELECTED_BY_FILTRATION("Suspended Matter Selected by Filtration"),
    @XmlEnumValue("Evaporated Dryless")
    EVAPORATED_DRYLESS("Evaporated Dryless"),
    @XmlEnumValue("Homogenisation")
    HOMOGENISATION("Homogenisation"),
    @XmlEnumValue("Liquid Reduced to 50% of its Original Volume")
    LIQUID_REDUCED_TO_50_OF_ITS_ORIGINAL_VOLUME("Liquid Reduced to 50% of its Original Volume"),
    @XmlEnumValue("Cleaned and Mixed")
    CLEANED_AND_MIXED("Cleaned and Mixed"),
    @XmlEnumValue("Pulverisation and Homogenisation")
    PULVERISATION_AND_HOMOGENISATION("Pulverisation and Homogenisation"),
    @XmlEnumValue("Air Dried if Necessary, Stones Removed")
    AIR_DRIED_IF_NECESSARY_STONES_REMOVED("Air Dried if Necessary, Stones Removed"),
    @XmlEnumValue("Sample Washed")
    SAMPLE_WASHED("Sample Washed"),
    @XmlEnumValue("Evaporation + Ashing, Filtering + Ashing")
    EVAPORATION_ASHING_FILTERING_ASHING("Evaporation + Ashing, Filtering + Ashing"),
    @XmlEnumValue("Dried + Homogenised")
    DRIED_HOMOGENISED("Dried + Homogenised"),
    @XmlEnumValue("Mixed")
    MIXED("Mixed"),
    @XmlEnumValue("No Treatment")
    NO_TREATMENT("No Treatment");
    private final String value;

    SampleTreatmentType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SampleTreatmentType fromValue(String v) {
        for (SampleTreatmentType c: SampleTreatmentType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
