//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.meteorology;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.iaea._2012.irix.format.base.FreeTextType;
import org.iaea._2012.irix.format.base.LengthType;
import org.iaea._2012.irix.format.base.PercentageType;
import org.iaea._2012.irix.format.locations.LocationOrLocationRefType;


/**
 * <p>Java class for MeteoRecordType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MeteoRecordType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Type" type="{http://www.iaea.org/2012/IRIX/Format/Meteorology}MeteoInfoType" minOccurs="0"/>
 *         &lt;element ref="{http://www.iaea.org/2012/IRIX/Format/Locations}Location"/>
 *         &lt;element name="ValidForPeriod" type="{http://www.iaea.org/2012/IRIX/Format/Meteorology}ValidForPeriodType"/>
 *         &lt;element name="WeatherCode" type="{http://www.iaea.org/2012/IRIX/Format/Meteorology}WeatherCodeType" minOccurs="0"/>
 *         &lt;element name="Temperature" type="{http://www.iaea.org/2012/IRIX/Format/Meteorology}TemperatureType" minOccurs="0"/>
 *         &lt;element name="DewPointTemperature" type="{http://www.iaea.org/2012/IRIX/Format/Meteorology}TemperatureType" minOccurs="0"/>
 *         &lt;element name="WindSpeed" type="{http://www.iaea.org/2012/IRIX/Format/Meteorology}WindSpeedType" minOccurs="0"/>
 *         &lt;element name="WindDirection" type="{http://www.iaea.org/2012/IRIX/Format/Meteorology}WindDirectionType" minOccurs="0"/>
 *         &lt;element name="Pressure" type="{http://www.iaea.org/2012/IRIX/Format/Meteorology}PressureType" minOccurs="0"/>
 *         &lt;element name="RelativeHumidity" type="{http://www.iaea.org/2012/IRIX/Format/Base}PercentageType" minOccurs="0"/>
 *         &lt;element name="CloudCover" type="{http://www.iaea.org/2012/IRIX/Format/Meteorology}CloudCoverType" minOccurs="0"/>
 *         &lt;element name="SolarRadiation" type="{http://www.iaea.org/2012/IRIX/Format/Meteorology}SolarRadiationType" minOccurs="0"/>
 *         &lt;element name="PasquillStabilityClass" type="{http://www.iaea.org/2012/IRIX/Format/Meteorology}PasquillStabilityClassType" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="InversionLayerHeight" type="{http://www.iaea.org/2012/IRIX/Format/Base}LengthType"/>
 *           &lt;element name="InversionHeightRange" type="{http://www.iaea.org/2012/IRIX/Format/Meteorology}InversionHeightRangeType"/>
 *         &lt;/choice>
 *         &lt;element name="Precipitation" type="{http://www.iaea.org/2012/IRIX/Format/Meteorology}PrecipitationType" minOccurs="0"/>
 *         &lt;element name="WeatherDescription" type="{http://www.iaea.org/2012/IRIX/Format/Base}FreeTextType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeteoRecordType", propOrder = {
    "type",
    "location",
    "validForPeriod",
    "weatherCode",
    "temperature",
    "dewPointTemperature",
    "windSpeed",
    "windDirection",
    "pressure",
    "relativeHumidity",
    "cloudCover",
    "solarRadiation",
    "pasquillStabilityClass",
    "inversionLayerHeight",
    "inversionHeightRange",
    "precipitation",
    "weatherDescription"
})
public class MeteoRecordType {

    @XmlElement(name = "Type")
    protected MeteoInfoType type;
    @XmlElement(name = "Location", namespace = "http://www.iaea.org/2012/IRIX/Format/Locations", required = true)
    protected LocationOrLocationRefType location;
    @XmlElement(name = "ValidForPeriod", required = true)
    protected ValidForPeriodType validForPeriod;
    @XmlElement(name = "WeatherCode")
    protected Integer weatherCode;
    @XmlElement(name = "Temperature")
    protected TemperatureType temperature;
    @XmlElement(name = "DewPointTemperature")
    protected TemperatureType dewPointTemperature;
    @XmlElement(name = "WindSpeed")
    protected WindSpeedType windSpeed;
    @XmlElement(name = "WindDirection")
    protected WindDirectionType windDirection;
    @XmlElement(name = "Pressure")
    protected PressureType pressure;
    @XmlElement(name = "RelativeHumidity")
    protected PercentageType relativeHumidity;
    @XmlElement(name = "CloudCover")
    protected Integer cloudCover;
    @XmlElement(name = "SolarRadiation")
    protected SolarRadiationType solarRadiation;
    @XmlElement(name = "PasquillStabilityClass")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String pasquillStabilityClass;
    @XmlElement(name = "InversionLayerHeight")
    protected LengthType inversionLayerHeight;
    @XmlElement(name = "InversionHeightRange")
    protected InversionHeightRangeType inversionHeightRange;
    @XmlElement(name = "Precipitation")
    protected PrecipitationType precipitation;
    @XmlElement(name = "WeatherDescription")
    protected FreeTextType weatherDescription;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link MeteoInfoType }
     *     
     */
    public MeteoInfoType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeteoInfoType }
     *     
     */
    public void setType(MeteoInfoType value) {
        this.type = value;
    }

    /**
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;html:p xmlns:html="http://www.w3.org/1999/xhtml" xmlns:base="http://www.iaea.org/2012/IRIX/Format/Base" xmlns:loc="http://www.iaea.org/2012/IRIX/Format/Locations" xmlns:meteo="http://www.iaea.org/2012/IRIX/Format/Meteorology" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;
     * 							Location for which weather is described.
     * 						&lt;/html:p&gt;
     * </pre>
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;html:p xmlns:html="http://www.w3.org/1999/xhtml" xmlns:base="http://www.iaea.org/2012/IRIX/Format/Base" xmlns:loc="http://www.iaea.org/2012/IRIX/Format/Locations" xmlns:meteo="http://www.iaea.org/2012/IRIX/Format/Meteorology" xmlns:xsd="http://www.w3.org/2001/XMLSchema" class="note"&gt;
     * 							For the structure of this element, see Locations section.
     * 						&lt;/html:p&gt;
     * </pre>
     * 
     * 					
     * 
     * @return
     *     possible object is
     *     {@link LocationOrLocationRefType }
     *     
     */
    public LocationOrLocationRefType getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationOrLocationRefType }
     *     
     */
    public void setLocation(LocationOrLocationRefType value) {
        this.location = value;
    }

    /**
     * Gets the value of the validForPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link ValidForPeriodType }
     *     
     */
    public ValidForPeriodType getValidForPeriod() {
        return validForPeriod;
    }

    /**
     * Sets the value of the validForPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidForPeriodType }
     *     
     */
    public void setValidForPeriod(ValidForPeriodType value) {
        this.validForPeriod = value;
    }

    /**
     * Gets the value of the weatherCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWeatherCode() {
        return weatherCode;
    }

    /**
     * Sets the value of the weatherCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWeatherCode(Integer value) {
        this.weatherCode = value;
    }

    /**
     * Gets the value of the temperature property.
     * 
     * @return
     *     possible object is
     *     {@link TemperatureType }
     *     
     */
    public TemperatureType getTemperature() {
        return temperature;
    }

    /**
     * Sets the value of the temperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemperatureType }
     *     
     */
    public void setTemperature(TemperatureType value) {
        this.temperature = value;
    }

    /**
     * Gets the value of the dewPointTemperature property.
     * 
     * @return
     *     possible object is
     *     {@link TemperatureType }
     *     
     */
    public TemperatureType getDewPointTemperature() {
        return dewPointTemperature;
    }

    /**
     * Sets the value of the dewPointTemperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemperatureType }
     *     
     */
    public void setDewPointTemperature(TemperatureType value) {
        this.dewPointTemperature = value;
    }

    /**
     * Gets the value of the windSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link WindSpeedType }
     *     
     */
    public WindSpeedType getWindSpeed() {
        return windSpeed;
    }

    /**
     * Sets the value of the windSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link WindSpeedType }
     *     
     */
    public void setWindSpeed(WindSpeedType value) {
        this.windSpeed = value;
    }

    /**
     * Gets the value of the windDirection property.
     * 
     * @return
     *     possible object is
     *     {@link WindDirectionType }
     *     
     */
    public WindDirectionType getWindDirection() {
        return windDirection;
    }

    /**
     * Sets the value of the windDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link WindDirectionType }
     *     
     */
    public void setWindDirection(WindDirectionType value) {
        this.windDirection = value;
    }

    /**
     * Gets the value of the pressure property.
     * 
     * @return
     *     possible object is
     *     {@link PressureType }
     *     
     */
    public PressureType getPressure() {
        return pressure;
    }

    /**
     * Sets the value of the pressure property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressureType }
     *     
     */
    public void setPressure(PressureType value) {
        this.pressure = value;
    }

    /**
     * Gets the value of the relativeHumidity property.
     * 
     * @return
     *     possible object is
     *     {@link PercentageType }
     *     
     */
    public PercentageType getRelativeHumidity() {
        return relativeHumidity;
    }

    /**
     * Sets the value of the relativeHumidity property.
     * 
     * @param value
     *     allowed object is
     *     {@link PercentageType }
     *     
     */
    public void setRelativeHumidity(PercentageType value) {
        this.relativeHumidity = value;
    }

    /**
     * Gets the value of the cloudCover property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCloudCover() {
        return cloudCover;
    }

    /**
     * Sets the value of the cloudCover property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCloudCover(Integer value) {
        this.cloudCover = value;
    }

    /**
     * Gets the value of the solarRadiation property.
     * 
     * @return
     *     possible object is
     *     {@link SolarRadiationType }
     *     
     */
    public SolarRadiationType getSolarRadiation() {
        return solarRadiation;
    }

    /**
     * Sets the value of the solarRadiation property.
     * 
     * @param value
     *     allowed object is
     *     {@link SolarRadiationType }
     *     
     */
    public void setSolarRadiation(SolarRadiationType value) {
        this.solarRadiation = value;
    }

    /**
     * Gets the value of the pasquillStabilityClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPasquillStabilityClass() {
        return pasquillStabilityClass;
    }

    /**
     * Sets the value of the pasquillStabilityClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPasquillStabilityClass(String value) {
        this.pasquillStabilityClass = value;
    }

    /**
     * Gets the value of the inversionLayerHeight property.
     * 
     * @return
     *     possible object is
     *     {@link LengthType }
     *     
     */
    public LengthType getInversionLayerHeight() {
        return inversionLayerHeight;
    }

    /**
     * Sets the value of the inversionLayerHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthType }
     *     
     */
    public void setInversionLayerHeight(LengthType value) {
        this.inversionLayerHeight = value;
    }

    /**
     * Gets the value of the inversionHeightRange property.
     * 
     * @return
     *     possible object is
     *     {@link InversionHeightRangeType }
     *     
     */
    public InversionHeightRangeType getInversionHeightRange() {
        return inversionHeightRange;
    }

    /**
     * Sets the value of the inversionHeightRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link InversionHeightRangeType }
     *     
     */
    public void setInversionHeightRange(InversionHeightRangeType value) {
        this.inversionHeightRange = value;
    }

    /**
     * Gets the value of the precipitation property.
     * 
     * @return
     *     possible object is
     *     {@link PrecipitationType }
     *     
     */
    public PrecipitationType getPrecipitation() {
        return precipitation;
    }

    /**
     * Sets the value of the precipitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrecipitationType }
     *     
     */
    public void setPrecipitation(PrecipitationType value) {
        this.precipitation = value;
    }

    /**
     * Gets the value of the weatherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link FreeTextType }
     *     
     */
    public FreeTextType getWeatherDescription() {
        return weatherDescription;
    }

    /**
     * Sets the value of the weatherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeTextType }
     *     
     */
    public void setWeatherDescription(FreeTextType value) {
        this.weatherDescription = value;
    }

}
