//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.meteorology;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrecipitationFormType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PrecipitationFormType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Rain"/>
 *     &lt;enumeration value="Light Rain"/>
 *     &lt;enumeration value="Heavy Rain"/>
 *     &lt;enumeration value="Snow"/>
 *     &lt;enumeration value="Rain and Snow Mixed"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PrecipitationFormType")
@XmlEnum
public enum PrecipitationFormType {

    @XmlEnumValue("Rain")
    RAIN("Rain"),
    @XmlEnumValue("Light Rain")
    LIGHT_RAIN("Light Rain"),
    @XmlEnumValue("Heavy Rain")
    HEAVY_RAIN("Heavy Rain"),
    @XmlEnumValue("Snow")
    SNOW("Snow"),
    @XmlEnumValue("Rain and Snow Mixed")
    RAIN_AND_SNOW_MIXED("Rain and Snow Mixed");
    private final String value;

    PrecipitationFormType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PrecipitationFormType fromValue(String v) {
        for (PrecipitationFormType c: PrecipitationFormType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
