//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.meteorology;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.iaea._2012.irix.format.base.YesNoUnknownType;


/**
 * <p>Java class for PrecipitationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrecipitationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Occurrence" type="{http://www.iaea.org/2012/IRIX/Format/Base}YesNoUnknownType"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="Form" type="{http://www.iaea.org/2012/IRIX/Format/Meteorology}PrecipitationFormType"/>
 *           &lt;element name="FormDescription" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;/choice>
 *         &lt;element name="Amount" type="{http://www.iaea.org/2012/IRIX/Format/Meteorology}PrecipitationAmountType" minOccurs="0"/>
 *         &lt;element name="Intensity" type="{http://www.iaea.org/2012/IRIX/Format/Meteorology}PrecipitationIntensityType" minOccurs="0"/>
 *         &lt;element name="SnowInformation" type="{http://www.iaea.org/2012/IRIX/Format/Meteorology}SnowInformationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrecipitationType", propOrder = {
    "occurrence",
    "form",
    "formDescription",
    "amount",
    "intensity",
    "snowInformation"
})
public class PrecipitationType {

    @XmlElement(name = "Occurrence", required = true)
    protected YesNoUnknownType occurrence;
    @XmlElement(name = "Form")
    protected PrecipitationFormType form;
    @XmlElement(name = "FormDescription")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String formDescription;
    @XmlElement(name = "Amount")
    protected PrecipitationAmountType amount;
    @XmlElement(name = "Intensity")
    protected PrecipitationIntensityType intensity;
    @XmlElement(name = "SnowInformation")
    protected SnowInformationType snowInformation;

    /**
     * Gets the value of the occurrence property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoUnknownType }
     *     
     */
    public YesNoUnknownType getOccurrence() {
        return occurrence;
    }

    /**
     * Sets the value of the occurrence property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoUnknownType }
     *     
     */
    public void setOccurrence(YesNoUnknownType value) {
        this.occurrence = value;
    }

    /**
     * Gets the value of the form property.
     * 
     * @return
     *     possible object is
     *     {@link PrecipitationFormType }
     *     
     */
    public PrecipitationFormType getForm() {
        return form;
    }

    /**
     * Sets the value of the form property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrecipitationFormType }
     *     
     */
    public void setForm(PrecipitationFormType value) {
        this.form = value;
    }

    /**
     * Gets the value of the formDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormDescription() {
        return formDescription;
    }

    /**
     * Sets the value of the formDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormDescription(String value) {
        this.formDescription = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link PrecipitationAmountType }
     *     
     */
    public PrecipitationAmountType getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrecipitationAmountType }
     *     
     */
    public void setAmount(PrecipitationAmountType value) {
        this.amount = value;
    }

    /**
     * Gets the value of the intensity property.
     * 
     * @return
     *     possible object is
     *     {@link PrecipitationIntensityType }
     *     
     */
    public PrecipitationIntensityType getIntensity() {
        return intensity;
    }

    /**
     * Sets the value of the intensity property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrecipitationIntensityType }
     *     
     */
    public void setIntensity(PrecipitationIntensityType value) {
        this.intensity = value;
    }

    /**
     * Gets the value of the snowInformation property.
     * 
     * @return
     *     possible object is
     *     {@link SnowInformationType }
     *     
     */
    public SnowInformationType getSnowInformation() {
        return snowInformation;
    }

    /**
     * Sets the value of the snowInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link SnowInformationType }
     *     
     */
    public void setSnowInformation(SnowInformationType value) {
        this.snowInformation = value;
    }

}
