//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.meteorology;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import org.iaea._2012.irix.format.base.AngleType;


/**
 * <p>Java class for WindDirectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WindDirectionType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.iaea.org/2012/IRIX/Format/Base>AngleType">
 *       &lt;attribute name="Fluctuation" type="{http://www.iaea.org/2012/IRIX/Format/Base}AngleValueType" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WindDirectionType")
public class WindDirectionType
    extends AngleType
{

    @XmlAttribute(name = "Fluctuation")
    protected BigDecimal fluctuation;

    /**
     * Gets the value of the fluctuation property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFluctuation() {
        return fluctuation;
    }

    /**
     * Sets the value of the fluctuation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFluctuation(BigDecimal value) {
        this.fluctuation = value;
    }

}
