//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.16 at 10:55:05 AM CET 
//


package org.iaea._2012.irix.format.identification;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import org.w3c.dom.Element;


/**
 * <p>Java class for IdentificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IdentificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrganisationReporting" type="{http://www.iaea.org/2012/IRIX/Format/Base}OrganisationIdentifierType"/>
 *         &lt;element name="DateAndTimeOfCreation" type="{http://www.iaea.org/2012/IRIX/Format/Base}DateTimeType"/>
 *         &lt;element name="ReportContext" type="{http://www.iaea.org/2012/IRIX/Format/Identification}ReportContextType"/>
 *         &lt;element name="SequenceNumber" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="ReportUUID" type="{http://www.iaea.org/2012/IRIX/Format/Base}UUIDType"/>
 *         &lt;element name="Follows" type="{http://www.iaea.org/2012/IRIX/Format/Base}UUIDType" minOccurs="0"/>
 *         &lt;element name="Revokes" type="{http://www.iaea.org/2012/IRIX/Format/Base}UUIDType" minOccurs="0"/>
 *         &lt;element name="Confidentiality" type="{http://www.iaea.org/2012/IRIX/Format/Identification}ConfidentialityType" minOccurs="0"/>
 *         &lt;element name="Addressees" type="{http://www.iaea.org/2012/IRIX/Format/Identification}AddresseesType" minOccurs="0"/>
 *         &lt;element name="ReportingBases" type="{http://www.iaea.org/2012/IRIX/Format/Identification}ReportingBasesType" minOccurs="0"/>
 *         &lt;element name="ContactPerson" type="{http://www.iaea.org/2012/IRIX/Format/Base}PersonIdentifierType" minOccurs="0"/>
 *         &lt;element name="AdditionalInformationURL" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="EventIdentifications" type="{http://www.iaea.org/2012/IRIX/Format/Identification}EventIdentificationsType" minOccurs="0"/>
 *         &lt;element name="Identifications" type="{http://www.iaea.org/2012/IRIX/Format/Identification}IdentificationsType"/>
 *         &lt;any processContents='skip' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 *  
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IdentificationType", propOrder = {
    "organisationReporting",
    "dateAndTimeOfCreation",
    "reportContext",
    "sequenceNumber",
    "reportUUID",
    "follows",
    "revokes",
    "confidentiality",
    "addressees",
    "reportingBases",
    "contactPerson",
    "additionalInformationURL",
    "eventIdentifications",
    "identifications",
    "any"
})
public class IdentificationType {

    @XmlElement(name = "OrganisationReporting", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String organisationReporting;
    @XmlElement(name = "DateAndTimeOfCreation", required = true)
    protected XMLGregorianCalendar dateAndTimeOfCreation;
    @XmlElement(name = "ReportContext", required = true)
    protected ReportContextType reportContext;
    @XmlElement(name = "SequenceNumber")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger sequenceNumber;
    @XmlElement(name = "ReportUUID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String reportUUID;
    @XmlElement(name = "Follows")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String follows;
    @XmlElement(name = "Revokes")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String revokes;
    @XmlElement(name = "Confidentiality")
    protected ConfidentialityType confidentiality;
    @XmlElement(name = "Addressees")
    protected AddresseesType addressees;
    @XmlElement(name = "ReportingBases")
    protected ReportingBasesType reportingBases;
    @XmlElement(name = "ContactPerson")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String contactPerson;
    @XmlElement(name = "AdditionalInformationURL")
    @XmlSchemaType(name = "anyURI")
    protected String additionalInformationURL;
    @XmlElement(name = "EventIdentifications")
    protected EventIdentificationsType eventIdentifications;
    @XmlElement(name = "Identifications", required = true)
    protected IdentificationsType identifications;
    @XmlAnyElement
    protected List<Element> any;

    /**
     * Gets the value of the organisationReporting property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganisationReporting() {
        return organisationReporting;
    }

    /**
     * Sets the value of the organisationReporting property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganisationReporting(String value) {
        this.organisationReporting = value;
    }

    /**
     * Gets the value of the dateAndTimeOfCreation property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateAndTimeOfCreation() {
        return dateAndTimeOfCreation;
    }

    /**
     * Sets the value of the dateAndTimeOfCreation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateAndTimeOfCreation(XMLGregorianCalendar value) {
        this.dateAndTimeOfCreation = value;
    }

    /**
     * Gets the value of the reportContext property.
     * 
     * @return
     *     possible object is
     *     {@link ReportContextType }
     *     
     */
    public ReportContextType getReportContext() {
        return reportContext;
    }

    /**
     * Sets the value of the reportContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportContextType }
     *     
     */
    public void setReportContext(ReportContextType value) {
        this.reportContext = value;
    }

    /**
     * Gets the value of the sequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * Sets the value of the sequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSequenceNumber(BigInteger value) {
        this.sequenceNumber = value;
    }

    /**
     * Gets the value of the reportUUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportUUID() {
        return reportUUID;
    }

    /**
     * Sets the value of the reportUUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportUUID(String value) {
        this.reportUUID = value;
    }

    /**
     * Gets the value of the follows property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFollows() {
        return follows;
    }

    /**
     * Sets the value of the follows property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFollows(String value) {
        this.follows = value;
    }

    /**
     * Gets the value of the revokes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevokes() {
        return revokes;
    }

    /**
     * Sets the value of the revokes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevokes(String value) {
        this.revokes = value;
    }

    /**
     * Gets the value of the confidentiality property.
     * 
     * @return
     *     possible object is
     *     {@link ConfidentialityType }
     *     
     */
    public ConfidentialityType getConfidentiality() {
        return confidentiality;
    }

    /**
     * Sets the value of the confidentiality property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfidentialityType }
     *     
     */
    public void setConfidentiality(ConfidentialityType value) {
        this.confidentiality = value;
    }

    /**
     * Gets the value of the addressees property.
     * 
     * @return
     *     possible object is
     *     {@link AddresseesType }
     *     
     */
    public AddresseesType getAddressees() {
        return addressees;
    }

    /**
     * Sets the value of the addressees property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddresseesType }
     *     
     */
    public void setAddressees(AddresseesType value) {
        this.addressees = value;
    }

    /**
     * Gets the value of the reportingBases property.
     * 
     * @return
     *     possible object is
     *     {@link ReportingBasesType }
     *     
     */
    public ReportingBasesType getReportingBases() {
        return reportingBases;
    }

    /**
     * Sets the value of the reportingBases property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportingBasesType }
     *     
     */
    public void setReportingBases(ReportingBasesType value) {
        this.reportingBases = value;
    }

    /**
     * Gets the value of the contactPerson property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * Sets the value of the contactPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactPerson(String value) {
        this.contactPerson = value;
    }

    /**
     * Gets the value of the additionalInformationURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalInformationURL() {
        return additionalInformationURL;
    }

    /**
     * Sets the value of the additionalInformationURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalInformationURL(String value) {
        this.additionalInformationURL = value;
    }

    /**
     * Gets the value of the eventIdentifications property.
     * 
     * @return
     *     possible object is
     *     {@link EventIdentificationsType }
     *     
     */
    public EventIdentificationsType getEventIdentifications() {
        return eventIdentifications;
    }

    /**
     * Sets the value of the eventIdentifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventIdentificationsType }
     *     
     */
    public void setEventIdentifications(EventIdentificationsType value) {
        this.eventIdentifications = value;
    }

    /**
     * Gets the value of the identifications property.
     * 
     * @return
     *     possible object is
     *     {@link IdentificationsType }
     *     
     */
    public IdentificationsType getIdentifications() {
        return identifications;
    }

    /**
     * Sets the value of the identifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentificationsType }
     *     
     */
    public void setIdentifications(IdentificationsType value) {
        this.identifications = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * 
     * 
     */
    public List<Element> getAny() {
        if (any == null) {
            any = new ArrayList<Element>();
        }
        return this.any;
    }

}
