//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.16 at 10:55:05 AM CET 
//


package org.iaea._2012.irix.format.identification;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.iaea._2012.irix.format.base.OrganisationContactType;
import org.iaea._2012.irix.format.base.PersonContactType;


/**
 * <p>Java class for IdentificationsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IdentificationsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.iaea.org/2012/IRIX/Format/Base}PersonContactInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.iaea.org/2012/IRIX/Format/Base}OrganisationContactInfo" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IdentificationsType", propOrder = {
    "personContactInfo",
    "organisationContactInfo"
})
public class IdentificationsType {

    @XmlElement(name = "PersonContactInfo", namespace = "http://www.iaea.org/2012/IRIX/Format/Base")
    protected List<PersonContactType> personContactInfo;
    @XmlElement(name = "OrganisationContactInfo", namespace = "http://www.iaea.org/2012/IRIX/Format/Base", required = true)
    protected List<OrganisationContactType> organisationContactInfo;

    /**
     * 
     * 						Contact information of the contact person for this report.
     * 					Gets the value of the personContactInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personContactInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonContactInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonContactType }
     * 
     * 
     */
    public List<PersonContactType> getPersonContactInfo() {
        if (personContactInfo == null) {
            personContactInfo = new ArrayList<PersonContactType>();
        }
        return this.personContactInfo;
    }

    /**
     * 
     * 						Contact information of the reporting organisation, and any addressed organisations, of this report.
     * 					Gets the value of the organisationContactInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organisationContactInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrganisationContactInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrganisationContactType }
     * 
     * 
     */
    public List<OrganisationContactType> getOrganisationContactInfo() {
        if (organisationContactInfo == null) {
            organisationContactInfo = new ArrayList<OrganisationContactType>();
        }
        return this.organisationContactInfo;
    }

}
