//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.16 at 10:55:05 AM CET 
//


package org.iaea._2012.irix.format.identification;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.iaea._2012.irix.format.identification package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Identification_QNAME = new QName("http://www.iaea.org/2012/IRIX/Format/Identification", "Identification");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.iaea._2012.irix.format.identification
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IdentificationType }
     * 
     */
    public IdentificationType createIdentificationType() {
        return new IdentificationType();
    }

    /**
     * Create an instance of {@link ReportingBasesType }
     * 
     */
    public ReportingBasesType createReportingBasesType() {
        return new ReportingBasesType();
    }

    /**
     * Create an instance of {@link EventIdentificationsType }
     * 
     */
    public EventIdentificationsType createEventIdentificationsType() {
        return new EventIdentificationsType();
    }

    /**
     * Create an instance of {@link IdentificationsType }
     * 
     */
    public IdentificationsType createIdentificationsType() {
        return new IdentificationsType();
    }

    /**
     * Create an instance of {@link EventIdentificationType }
     * 
     */
    public EventIdentificationType createEventIdentificationType() {
        return new EventIdentificationType();
    }

    /**
     * Create an instance of {@link AddresseesType }
     * 
     */
    public AddresseesType createAddresseesType() {
        return new AddresseesType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iaea.org/2012/IRIX/Format/Identification", name = "Identification")
    public JAXBElement<IdentificationType> createIdentification(IdentificationType value) {
        return new JAXBElement<IdentificationType>(_Identification_QNAME, IdentificationType.class, null, value);
    }

}
