//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.16 at 10:55:05 AM CET 
//


package org.iaea._2012.irix.format.base;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.iaea._2012.irix.format.base package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OrganisationContactInfo_QNAME = new QName("http://www.iaea.org/2012/IRIX/Format/Base", "OrganisationContactInfo");
    private final static QName _PersonContactInfo_QNAME = new QName("http://www.iaea.org/2012/IRIX/Format/Base", "PersonContactInfo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.iaea._2012.irix.format.base
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OrganisationContactType }
     * 
     */
    public OrganisationContactType createOrganisationContactType() {
        return new OrganisationContactType();
    }

    /**
     * Create an instance of {@link PersonContactType }
     * 
     */
    public PersonContactType createPersonContactType() {
        return new PersonContactType();
    }

    /**
     * Create an instance of {@link LengthType }
     * 
     */
    public LengthType createLengthType() {
        return new LengthType();
    }

    /**
     * Create an instance of {@link InformationBlock }
     * 
     */
    public InformationBlock createInformationBlock() {
        return new InformationBlock();
    }

    /**
     * Create an instance of {@link PercentageType }
     * 
     */
    public PercentageType createPercentageType() {
        return new PercentageType();
    }

    /**
     * Create an instance of {@link FreeTextType }
     * 
     */
    public FreeTextType createFreeTextType() {
        return new FreeTextType();
    }

    /**
     * Create an instance of {@link AngleType }
     * 
     */
    public AngleType createAngleType() {
        return new AngleType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganisationContactType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iaea.org/2012/IRIX/Format/Base", name = "OrganisationContactInfo")
    public JAXBElement<OrganisationContactType> createOrganisationContactInfo(OrganisationContactType value) {
        return new JAXBElement<OrganisationContactType>(_OrganisationContactInfo_QNAME, OrganisationContactType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonContactType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iaea.org/2012/IRIX/Format/Base", name = "PersonContactInfo")
    public JAXBElement<PersonContactType> createPersonContactInfo(PersonContactType value) {
        return new JAXBElement<PersonContactType>(_PersonContactInfo_QNAME, PersonContactType.class, null, value);
    }

}
