//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.releaseinformation;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ActualReleaseValueType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ActualReleaseValueType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Has Occurred"/>
 *     &lt;enumeration value="Has Not Occurred"/>
 *     &lt;enumeration value="Unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ActualReleaseValueType")
@XmlEnum
public enum ActualReleaseValueType {

    @XmlEnumValue("Has Occurred")
    HAS_OCCURRED("Has Occurred"),
    @XmlEnumValue("Has Not Occurred")
    HAS_NOT_OCCURRED("Has Not Occurred"),
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown");
    private final String value;

    ActualReleaseValueType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ActualReleaseValueType fromValue(String v) {
        for (ActualReleaseValueType c: ActualReleaseValueType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
