//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.releaseinformation;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FutureReleaseValueType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FutureReleaseValueType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Certain Not to Occur"/>
 *     &lt;enumeration value="Unlikely to Occur"/>
 *     &lt;enumeration value="Likely to Occur"/>
 *     &lt;enumeration value="Certain to Occur"/>
 *     &lt;enumeration value="Unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FutureReleaseValueType")
@XmlEnum
public enum FutureReleaseValueType {

    @XmlEnumValue("Certain Not to Occur")
    CERTAIN_NOT_TO_OCCUR("Certain Not to Occur"),
    @XmlEnumValue("Unlikely to Occur")
    UNLIKELY_TO_OCCUR("Unlikely to Occur"),
    @XmlEnumValue("Likely to Occur")
    LIKELY_TO_OCCUR("Likely to Occur"),
    @XmlEnumValue("Certain to Occur")
    CERTAIN_TO_OCCUR("Certain to Occur"),
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown");
    private final String value;

    FutureReleaseValueType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FutureReleaseValueType fromValue(String v) {
        for (FutureReleaseValueType c: FutureReleaseValueType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
