//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.releaseinformation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.iaea._2012.irix.format.base.YesNoUnknownType;


/**
 * <p>Java class for HeatEmissionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HeatEmissionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SignificantEmissionOfHeat" type="{http://www.iaea.org/2012/IRIX/Format/Base}YesNoUnknownType" minOccurs="0"/>
 *         &lt;element name="HeatEmissionRate" type="{http://www.iaea.org/2012/IRIX/Format/ReleaseInformation}HeatEmissionRateType" minOccurs="0"/>
 *         &lt;element name="AreaOfHeatEmission" type="{http://www.iaea.org/2012/IRIX/Format/ReleaseInformation}AreaOfHeatEmissionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HeatEmissionType", propOrder = {
    "significantEmissionOfHeat",
    "heatEmissionRate",
    "areaOfHeatEmission"
})
public class HeatEmissionType {

    @XmlElement(name = "SignificantEmissionOfHeat")
    protected YesNoUnknownType significantEmissionOfHeat;
    @XmlElement(name = "HeatEmissionRate")
    protected HeatEmissionRateType heatEmissionRate;
    @XmlElement(name = "AreaOfHeatEmission")
    protected AreaOfHeatEmissionType areaOfHeatEmission;

    /**
     * Gets the value of the significantEmissionOfHeat property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoUnknownType }
     *     
     */
    public YesNoUnknownType getSignificantEmissionOfHeat() {
        return significantEmissionOfHeat;
    }

    /**
     * Sets the value of the significantEmissionOfHeat property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoUnknownType }
     *     
     */
    public void setSignificantEmissionOfHeat(YesNoUnknownType value) {
        this.significantEmissionOfHeat = value;
    }

    /**
     * Gets the value of the heatEmissionRate property.
     * 
     * @return
     *     possible object is
     *     {@link HeatEmissionRateType }
     *     
     */
    public HeatEmissionRateType getHeatEmissionRate() {
        return heatEmissionRate;
    }

    /**
     * Sets the value of the heatEmissionRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeatEmissionRateType }
     *     
     */
    public void setHeatEmissionRate(HeatEmissionRateType value) {
        this.heatEmissionRate = value;
    }

    /**
     * Gets the value of the areaOfHeatEmission property.
     * 
     * @return
     *     possible object is
     *     {@link AreaOfHeatEmissionType }
     *     
     */
    public AreaOfHeatEmissionType getAreaOfHeatEmission() {
        return areaOfHeatEmission;
    }

    /**
     * Sets the value of the areaOfHeatEmission property.
     * 
     * @param value
     *     allowed object is
     *     {@link AreaOfHeatEmissionType }
     *     
     */
    public void setAreaOfHeatEmission(AreaOfHeatEmissionType value) {
        this.areaOfHeatEmission = value;
    }

}
