//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.releaseinformation;

import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for NuclideReleaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NuclideReleaseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.iaea.org/2012/IRIX/Format/ReleaseInformation}NuclideInfo"/>
 *         &lt;element name="Activity" type="{http://www.iaea.org/2012/IRIX/Format/ReleaseInformation}ReleaseAmountType"/>
 *         &lt;sequence>
 *           &lt;element name="MethodOfDetermination" type="{http://www.iaea.org/2012/IRIX/Format/ReleaseInformation}NuclideReleaseMethodOfDetermination"/>
 *           &lt;element name="MethodOfDeterminationDescription" type="{http://www.iaea.org/2012/IRIX/Format/Base}ShortStringType" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NuclideReleaseType", propOrder = {
    "nuclideInfo",
    "activity",
    "methodOfDetermination",
    "methodOfDeterminationDescription"
})
public class NuclideReleaseType {

    @XmlElementRef(name = "NuclideInfo", namespace = "http://www.iaea.org/2012/IRIX/Format/ReleaseInformation", type = JAXBElement.class)
    protected JAXBElement<?> nuclideInfo;
    @XmlElement(name = "Activity", required = true)
    protected ReleaseAmountType activity;
    @XmlElement(name = "MethodOfDetermination", required = true)
    protected NuclideReleaseMethodOfDetermination methodOfDetermination;
    @XmlElement(name = "MethodOfDeterminationDescription")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String methodOfDeterminationDescription;

    /**
     * 
     * 						A nuclide, a list or a combination of nuclides,
     * 						specified using a pre-defined value or a free text description.
     * 					
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     {@link JAXBElement }{@code <}{@link NuclideCombinationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link List }{@code <}{@link String }{@code >}{@code >}
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<?> getNuclideInfo() {
        return nuclideInfo;
    }

    /**
     * Sets the value of the nuclideInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     {@link JAXBElement }{@code <}{@link NuclideCombinationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link List }{@code <}{@link String }{@code >}{@code >}
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setNuclideInfo(JAXBElement<?> value) {
        this.nuclideInfo = value;
    }

    /**
     * Gets the value of the activity property.
     * 
     * @return
     *     possible object is
     *     {@link ReleaseAmountType }
     *     
     */
    public ReleaseAmountType getActivity() {
        return activity;
    }

    /**
     * Sets the value of the activity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReleaseAmountType }
     *     
     */
    public void setActivity(ReleaseAmountType value) {
        this.activity = value;
    }

    /**
     * Gets the value of the methodOfDetermination property.
     * 
     * @return
     *     possible object is
     *     {@link NuclideReleaseMethodOfDetermination }
     *     
     */
    public NuclideReleaseMethodOfDetermination getMethodOfDetermination() {
        return methodOfDetermination;
    }

    /**
     * Sets the value of the methodOfDetermination property.
     * 
     * @param value
     *     allowed object is
     *     {@link NuclideReleaseMethodOfDetermination }
     *     
     */
    public void setMethodOfDetermination(NuclideReleaseMethodOfDetermination value) {
        this.methodOfDetermination = value;
    }

    /**
     * Gets the value of the methodOfDeterminationDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethodOfDeterminationDescription() {
        return methodOfDeterminationDescription;
    }

    /**
     * Sets the value of the methodOfDeterminationDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethodOfDeterminationDescription(String value) {
        this.methodOfDeterminationDescription = value;
    }

}
