//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.releaseinformation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.iaea._2012.irix.format.base.PercentageType;


/**
 * <p>Java class for RelativeIodineFractionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelativeIodineFractionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Elementary" type="{http://www.iaea.org/2012/IRIX/Format/Base}PercentageType"/>
 *         &lt;element name="Organic" type="{http://www.iaea.org/2012/IRIX/Format/Base}PercentageType"/>
 *         &lt;element name="Aerosol" type="{http://www.iaea.org/2012/IRIX/Format/Base}PercentageType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelativeIodineFractionsType", propOrder = {
    "elementary",
    "organic",
    "aerosol"
})
public class RelativeIodineFractionsType {

    @XmlElement(name = "Elementary", required = true)
    protected PercentageType elementary;
    @XmlElement(name = "Organic", required = true)
    protected PercentageType organic;
    @XmlElement(name = "Aerosol", required = true)
    protected PercentageType aerosol;

    /**
     * Gets the value of the elementary property.
     * 
     * @return
     *     possible object is
     *     {@link PercentageType }
     *     
     */
    public PercentageType getElementary() {
        return elementary;
    }

    /**
     * Sets the value of the elementary property.
     * 
     * @param value
     *     allowed object is
     *     {@link PercentageType }
     *     
     */
    public void setElementary(PercentageType value) {
        this.elementary = value;
    }

    /**
     * Gets the value of the organic property.
     * 
     * @return
     *     possible object is
     *     {@link PercentageType }
     *     
     */
    public PercentageType getOrganic() {
        return organic;
    }

    /**
     * Sets the value of the organic property.
     * 
     * @param value
     *     allowed object is
     *     {@link PercentageType }
     *     
     */
    public void setOrganic(PercentageType value) {
        this.organic = value;
    }

    /**
     * Gets the value of the aerosol property.
     * 
     * @return
     *     possible object is
     *     {@link PercentageType }
     *     
     */
    public PercentageType getAerosol() {
        return aerosol;
    }

    /**
     * Sets the value of the aerosol property.
     * 
     * @param value
     *     allowed object is
     *     {@link PercentageType }
     *     
     */
    public void setAerosol(PercentageType value) {
        this.aerosol = value;
    }

}
