//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.releaseinformation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.iaea._2012.irix.format.base.FreeTextType;
import org.iaea._2012.irix.format.base.YesNoUnknownType;


/**
 * <p>Java class for ReleaseToWaterPhaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReleaseToWaterPhaseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Occurrence" type="{http://www.iaea.org/2012/IRIX/Format/ReleaseInformation}ReleasePhaseOccurrenceType"/>
 *         &lt;element name="TimeOfRelease" type="{http://www.iaea.org/2012/IRIX/Format/ReleaseInformation}TimeOfReleaseType" minOccurs="0"/>
 *         &lt;element name="AffectedWaterBody" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="NuclideReleases" type="{http://www.iaea.org/2012/IRIX/Format/ReleaseInformation}NuclideReleasesType" minOccurs="0"/>
 *         &lt;element name="ChemicalHealthEffects" type="{http://www.iaea.org/2012/IRIX/Format/Base}YesNoUnknownType" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.iaea.org/2012/IRIX/Format/Base}FreeTextType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReleaseToWaterPhaseType", propOrder = {
    "occurrence",
    "timeOfRelease",
    "affectedWaterBody",
    "nuclideReleases",
    "chemicalHealthEffects",
    "description"
})
public class ReleaseToWaterPhaseType {

    @XmlElement(name = "Occurrence", required = true)
    protected ReleasePhaseOccurrenceType occurrence;
    @XmlElement(name = "TimeOfRelease")
    protected TimeOfReleaseType timeOfRelease;
    @XmlElement(name = "AffectedWaterBody", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String affectedWaterBody;
    @XmlElement(name = "NuclideReleases")
    protected NuclideReleasesType nuclideReleases;
    @XmlElement(name = "ChemicalHealthEffects")
    protected YesNoUnknownType chemicalHealthEffects;
    @XmlElement(name = "Description")
    protected FreeTextType description;

    /**
     * Gets the value of the occurrence property.
     * 
     * @return
     *     possible object is
     *     {@link ReleasePhaseOccurrenceType }
     *     
     */
    public ReleasePhaseOccurrenceType getOccurrence() {
        return occurrence;
    }

    /**
     * Sets the value of the occurrence property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReleasePhaseOccurrenceType }
     *     
     */
    public void setOccurrence(ReleasePhaseOccurrenceType value) {
        this.occurrence = value;
    }

    /**
     * Gets the value of the timeOfRelease property.
     * 
     * @return
     *     possible object is
     *     {@link TimeOfReleaseType }
     *     
     */
    public TimeOfReleaseType getTimeOfRelease() {
        return timeOfRelease;
    }

    /**
     * Sets the value of the timeOfRelease property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeOfReleaseType }
     *     
     */
    public void setTimeOfRelease(TimeOfReleaseType value) {
        this.timeOfRelease = value;
    }

    /**
     * Gets the value of the affectedWaterBody property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffectedWaterBody() {
        return affectedWaterBody;
    }

    /**
     * Sets the value of the affectedWaterBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffectedWaterBody(String value) {
        this.affectedWaterBody = value;
    }

    /**
     * Gets the value of the nuclideReleases property.
     * 
     * @return
     *     possible object is
     *     {@link NuclideReleasesType }
     *     
     */
    public NuclideReleasesType getNuclideReleases() {
        return nuclideReleases;
    }

    /**
     * Sets the value of the nuclideReleases property.
     * 
     * @param value
     *     allowed object is
     *     {@link NuclideReleasesType }
     *     
     */
    public void setNuclideReleases(NuclideReleasesType value) {
        this.nuclideReleases = value;
    }

    /**
     * Gets the value of the chemicalHealthEffects property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoUnknownType }
     *     
     */
    public YesNoUnknownType getChemicalHealthEffects() {
        return chemicalHealthEffects;
    }

    /**
     * Sets the value of the chemicalHealthEffects property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoUnknownType }
     *     
     */
    public void setChemicalHealthEffects(YesNoUnknownType value) {
        this.chemicalHealthEffects = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link FreeTextType }
     *     
     */
    public FreeTextType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeTextType }
     *     
     */
    public void setDescription(FreeTextType value) {
        this.description = value;
    }

}
