//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.releaseinformation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReleaseOccurrenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReleaseOccurrenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ActualRelease" type="{http://www.iaea.org/2012/IRIX/Format/ReleaseInformation}ActualReleaseType"/>
 *         &lt;element name="FutureRelease" type="{http://www.iaea.org/2012/IRIX/Format/ReleaseInformation}FutureReleaseType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReleaseOccurrenceType", propOrder = {
    "actualRelease",
    "futureRelease"
})
public class ReleaseOccurrenceType {

    @XmlElement(name = "ActualRelease", required = true)
    protected ActualReleaseType actualRelease;
    @XmlElement(name = "FutureRelease")
    protected FutureReleaseType futureRelease;

    /**
     * Gets the value of the actualRelease property.
     * 
     * @return
     *     possible object is
     *     {@link ActualReleaseType }
     *     
     */
    public ActualReleaseType getActualRelease() {
        return actualRelease;
    }

    /**
     * Sets the value of the actualRelease property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActualReleaseType }
     *     
     */
    public void setActualRelease(ActualReleaseType value) {
        this.actualRelease = value;
    }

    /**
     * Gets the value of the futureRelease property.
     * 
     * @return
     *     possible object is
     *     {@link FutureReleaseType }
     *     
     */
    public FutureReleaseType getFutureRelease() {
        return futureRelease;
    }

    /**
     * Sets the value of the futureRelease property.
     * 
     * @param value
     *     allowed object is
     *     {@link FutureReleaseType }
     *     
     */
    public void setFutureRelease(FutureReleaseType value) {
        this.futureRelease = value;
    }

}
