//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.releaseinformation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReleaseToAirType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReleaseToAirType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReleasePhases" type="{http://www.iaea.org/2012/IRIX/Format/ReleaseInformation}ReleaseToAirPhasesType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReleaseToAirType", propOrder = {
    "releasePhases"
})
public class ReleaseToAirType {

    @XmlElement(name = "ReleasePhases", required = true)
    protected ReleaseToAirPhasesType releasePhases;

    /**
     * Gets the value of the releasePhases property.
     * 
     * @return
     *     possible object is
     *     {@link ReleaseToAirPhasesType }
     *     
     */
    public ReleaseToAirPhasesType getReleasePhases() {
        return releasePhases;
    }

    /**
     * Sets the value of the releasePhases property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReleaseToAirPhasesType }
     *     
     */
    public void setReleasePhases(ReleaseToAirPhasesType value) {
        this.releasePhases = value;
    }

}
