//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.releaseinformation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.iaea._2012.irix.format.base.FreeTextType;
import org.iaea._2012.irix.format.base.YesNoUnknownType;


/**
 * <p>Java class for ReleaseToAirPhaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReleaseToAirPhaseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Occurrence" type="{http://www.iaea.org/2012/IRIX/Format/ReleaseInformation}ReleasePhaseOccurrenceType"/>
 *         &lt;element name="TimeOfRelease" type="{http://www.iaea.org/2012/IRIX/Format/ReleaseInformation}TimeOfReleaseType" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="ReleaseRoute" type="{http://www.iaea.org/2012/IRIX/Format/ReleaseInformation}ReleaseRouteType"/>
 *           &lt;element name="ReleaseRouteDescription" type="{http://www.iaea.org/2012/IRIX/Format/Base}ShortStringType"/>
 *         &lt;/choice>
 *         &lt;element name="ReleaseHeight" type="{http://www.iaea.org/2012/IRIX/Format/ReleaseInformation}ReleaseHeightType" minOccurs="0"/>
 *         &lt;element name="HeatEmission" type="{http://www.iaea.org/2012/IRIX/Format/ReleaseInformation}HeatEmissionType" minOccurs="0"/>
 *         &lt;element name="TypeOfRelease" type="{http://www.iaea.org/2012/IRIX/Format/ReleaseInformation}TypeOfReleaseType" minOccurs="0"/>
 *         &lt;element name="NuclideReleases" type="{http://www.iaea.org/2012/IRIX/Format/ReleaseInformation}NuclideReleasesType" minOccurs="0"/>
 *         &lt;element name="RelativeIodineFractions" type="{http://www.iaea.org/2012/IRIX/Format/ReleaseInformation}RelativeIodineFractionsType" minOccurs="0"/>
 *         &lt;element name="ChemicalHealthEffects" type="{http://www.iaea.org/2012/IRIX/Format/Base}YesNoUnknownType" minOccurs="0"/>
 *         &lt;element name="PlumeCharacteristics" type="{http://www.iaea.org/2012/IRIX/Format/ReleaseInformation}PlumeCharacteristicsType" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.iaea.org/2012/IRIX/Format/Base}FreeTextType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReleaseToAirPhaseType", propOrder = {
    "occurrence",
    "timeOfRelease",
    "releaseRoute",
    "releaseRouteDescription",
    "releaseHeight",
    "heatEmission",
    "typeOfRelease",
    "nuclideReleases",
    "relativeIodineFractions",
    "chemicalHealthEffects",
    "plumeCharacteristics",
    "description"
})
public class ReleaseToAirPhaseType {

    @XmlElement(name = "Occurrence", required = true)
    protected ReleasePhaseOccurrenceType occurrence;
    @XmlElement(name = "TimeOfRelease")
    protected TimeOfReleaseType timeOfRelease;
    @XmlElement(name = "ReleaseRoute")
    protected ReleaseRouteType releaseRoute;
    @XmlElement(name = "ReleaseRouteDescription")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String releaseRouteDescription;
    @XmlElement(name = "ReleaseHeight")
    protected ReleaseHeightType releaseHeight;
    @XmlElement(name = "HeatEmission")
    protected HeatEmissionType heatEmission;
    @XmlElement(name = "TypeOfRelease")
    protected TypeOfReleaseType typeOfRelease;
    @XmlElement(name = "NuclideReleases")
    protected NuclideReleasesType nuclideReleases;
    @XmlElement(name = "RelativeIodineFractions")
    protected RelativeIodineFractionsType relativeIodineFractions;
    @XmlElement(name = "ChemicalHealthEffects")
    protected YesNoUnknownType chemicalHealthEffects;
    @XmlElement(name = "PlumeCharacteristics")
    protected PlumeCharacteristicsType plumeCharacteristics;
    @XmlElement(name = "Description")
    protected FreeTextType description;

    /**
     * Gets the value of the occurrence property.
     * 
     * @return
     *     possible object is
     *     {@link ReleasePhaseOccurrenceType }
     *     
     */
    public ReleasePhaseOccurrenceType getOccurrence() {
        return occurrence;
    }

    /**
     * Sets the value of the occurrence property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReleasePhaseOccurrenceType }
     *     
     */
    public void setOccurrence(ReleasePhaseOccurrenceType value) {
        this.occurrence = value;
    }

    /**
     * Gets the value of the timeOfRelease property.
     * 
     * @return
     *     possible object is
     *     {@link TimeOfReleaseType }
     *     
     */
    public TimeOfReleaseType getTimeOfRelease() {
        return timeOfRelease;
    }

    /**
     * Sets the value of the timeOfRelease property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeOfReleaseType }
     *     
     */
    public void setTimeOfRelease(TimeOfReleaseType value) {
        this.timeOfRelease = value;
    }

    /**
     * Gets the value of the releaseRoute property.
     * 
     * @return
     *     possible object is
     *     {@link ReleaseRouteType }
     *     
     */
    public ReleaseRouteType getReleaseRoute() {
        return releaseRoute;
    }

    /**
     * Sets the value of the releaseRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReleaseRouteType }
     *     
     */
    public void setReleaseRoute(ReleaseRouteType value) {
        this.releaseRoute = value;
    }

    /**
     * Gets the value of the releaseRouteDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReleaseRouteDescription() {
        return releaseRouteDescription;
    }

    /**
     * Sets the value of the releaseRouteDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReleaseRouteDescription(String value) {
        this.releaseRouteDescription = value;
    }

    /**
     * Gets the value of the releaseHeight property.
     * 
     * @return
     *     possible object is
     *     {@link ReleaseHeightType }
     *     
     */
    public ReleaseHeightType getReleaseHeight() {
        return releaseHeight;
    }

    /**
     * Sets the value of the releaseHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReleaseHeightType }
     *     
     */
    public void setReleaseHeight(ReleaseHeightType value) {
        this.releaseHeight = value;
    }

    /**
     * Gets the value of the heatEmission property.
     * 
     * @return
     *     possible object is
     *     {@link HeatEmissionType }
     *     
     */
    public HeatEmissionType getHeatEmission() {
        return heatEmission;
    }

    /**
     * Sets the value of the heatEmission property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeatEmissionType }
     *     
     */
    public void setHeatEmission(HeatEmissionType value) {
        this.heatEmission = value;
    }

    /**
     * Gets the value of the typeOfRelease property.
     * 
     * @return
     *     possible object is
     *     {@link TypeOfReleaseType }
     *     
     */
    public TypeOfReleaseType getTypeOfRelease() {
        return typeOfRelease;
    }

    /**
     * Sets the value of the typeOfRelease property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeOfReleaseType }
     *     
     */
    public void setTypeOfRelease(TypeOfReleaseType value) {
        this.typeOfRelease = value;
    }

    /**
     * Gets the value of the nuclideReleases property.
     * 
     * @return
     *     possible object is
     *     {@link NuclideReleasesType }
     *     
     */
    public NuclideReleasesType getNuclideReleases() {
        return nuclideReleases;
    }

    /**
     * Sets the value of the nuclideReleases property.
     * 
     * @param value
     *     allowed object is
     *     {@link NuclideReleasesType }
     *     
     */
    public void setNuclideReleases(NuclideReleasesType value) {
        this.nuclideReleases = value;
    }

    /**
     * Gets the value of the relativeIodineFractions property.
     * 
     * @return
     *     possible object is
     *     {@link RelativeIodineFractionsType }
     *     
     */
    public RelativeIodineFractionsType getRelativeIodineFractions() {
        return relativeIodineFractions;
    }

    /**
     * Sets the value of the relativeIodineFractions property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelativeIodineFractionsType }
     *     
     */
    public void setRelativeIodineFractions(RelativeIodineFractionsType value) {
        this.relativeIodineFractions = value;
    }

    /**
     * Gets the value of the chemicalHealthEffects property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoUnknownType }
     *     
     */
    public YesNoUnknownType getChemicalHealthEffects() {
        return chemicalHealthEffects;
    }

    /**
     * Sets the value of the chemicalHealthEffects property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoUnknownType }
     *     
     */
    public void setChemicalHealthEffects(YesNoUnknownType value) {
        this.chemicalHealthEffects = value;
    }

    /**
     * Gets the value of the plumeCharacteristics property.
     * 
     * @return
     *     possible object is
     *     {@link PlumeCharacteristicsType }
     *     
     */
    public PlumeCharacteristicsType getPlumeCharacteristics() {
        return plumeCharacteristics;
    }

    /**
     * Sets the value of the plumeCharacteristics property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlumeCharacteristicsType }
     *     
     */
    public void setPlumeCharacteristics(PlumeCharacteristicsType value) {
        this.plumeCharacteristics = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link FreeTextType }
     *     
     */
    public FreeTextType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeTextType }
     *     
     */
    public void setDescription(FreeTextType value) {
        this.description = value;
    }

}
