//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.releaseinformation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.iaea._2012.irix.format.base.InformationBlock;


/**
 * <p>Java class for ReleaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReleaseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iaea.org/2012/IRIX/Format/Base}InformationBlock">
 *       &lt;sequence>
 *         &lt;element name="ReleaseOccurrence" type="{http://www.iaea.org/2012/IRIX/Format/ReleaseInformation}ReleaseOccurrenceType" minOccurs="0"/>
 *         &lt;element name="ReleaseToAir" type="{http://www.iaea.org/2012/IRIX/Format/ReleaseInformation}ReleaseToAirType" minOccurs="0"/>
 *         &lt;element name="ReleaseToWater" type="{http://www.iaea.org/2012/IRIX/Format/ReleaseInformation}ReleaseToWaterType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReleaseType", propOrder = {
    "releaseOccurrence",
    "releaseToAir",
    "releaseToWater"
})
public class ReleaseType
    extends InformationBlock
{

    @XmlElement(name = "ReleaseOccurrence")
    protected ReleaseOccurrenceType releaseOccurrence;
    @XmlElement(name = "ReleaseToAir")
    protected ReleaseToAirType releaseToAir;
    @XmlElement(name = "ReleaseToWater")
    protected ReleaseToWaterType releaseToWater;

    /**
     * Gets the value of the releaseOccurrence property.
     * 
     * @return
     *     possible object is
     *     {@link ReleaseOccurrenceType }
     *     
     */
    public ReleaseOccurrenceType getReleaseOccurrence() {
        return releaseOccurrence;
    }

    /**
     * Sets the value of the releaseOccurrence property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReleaseOccurrenceType }
     *     
     */
    public void setReleaseOccurrence(ReleaseOccurrenceType value) {
        this.releaseOccurrence = value;
    }

    /**
     * Gets the value of the releaseToAir property.
     * 
     * @return
     *     possible object is
     *     {@link ReleaseToAirType }
     *     
     */
    public ReleaseToAirType getReleaseToAir() {
        return releaseToAir;
    }

    /**
     * Sets the value of the releaseToAir property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReleaseToAirType }
     *     
     */
    public void setReleaseToAir(ReleaseToAirType value) {
        this.releaseToAir = value;
    }

    /**
     * Gets the value of the releaseToWater property.
     * 
     * @return
     *     possible object is
     *     {@link ReleaseToWaterType }
     *     
     */
    public ReleaseToWaterType getReleaseToWater() {
        return releaseToWater;
    }

    /**
     * Sets the value of the releaseToWater property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReleaseToWaterType }
     *     
     */
    public void setReleaseToWater(ReleaseToWaterType value) {
        this.releaseToWater = value;
    }

}
