//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.medicalinformation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.iaea._2012.irix.format.base.FreeTextType;


/**
 * <p>Java class for AssessedDoseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssessedDoseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="TypeOfDose" type="{http://www.iaea.org/2012/IRIX/Format/MedicalInformation}TypeOfDoseType"/>
 *           &lt;element name="TypeOfDoseDescription" type="{http://www.iaea.org/2012/IRIX/Format/Base}ShortStringType"/>
 *         &lt;/choice>
 *         &lt;element name="DoseValue" type="{http://www.iaea.org/2012/IRIX/Format/MedicalInformation}DoseValueType"/>
 *         &lt;element name="DoseAssessmentMethod" type="{http://www.iaea.org/2012/IRIX/Format/Base}ShortStringType" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.iaea.org/2012/IRIX/Format/Base}FreeTextType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssessedDoseType", propOrder = {
    "typeOfDose",
    "typeOfDoseDescription",
    "doseValue",
    "doseAssessmentMethod",
    "description"
})
public class AssessedDoseType {

    @XmlElement(name = "TypeOfDose")
    protected TypeOfDoseType typeOfDose;
    @XmlElement(name = "TypeOfDoseDescription")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String typeOfDoseDescription;
    @XmlElement(name = "DoseValue", required = true)
    protected DoseValueType doseValue;
    @XmlElement(name = "DoseAssessmentMethod")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String doseAssessmentMethod;
    @XmlElement(name = "Description")
    protected FreeTextType description;

    /**
     * Gets the value of the typeOfDose property.
     * 
     * @return
     *     possible object is
     *     {@link TypeOfDoseType }
     *     
     */
    public TypeOfDoseType getTypeOfDose() {
        return typeOfDose;
    }

    /**
     * Sets the value of the typeOfDose property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeOfDoseType }
     *     
     */
    public void setTypeOfDose(TypeOfDoseType value) {
        this.typeOfDose = value;
    }

    /**
     * Gets the value of the typeOfDoseDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOfDoseDescription() {
        return typeOfDoseDescription;
    }

    /**
     * Sets the value of the typeOfDoseDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOfDoseDescription(String value) {
        this.typeOfDoseDescription = value;
    }

    /**
     * Gets the value of the doseValue property.
     * 
     * @return
     *     possible object is
     *     {@link DoseValueType }
     *     
     */
    public DoseValueType getDoseValue() {
        return doseValue;
    }

    /**
     * Sets the value of the doseValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoseValueType }
     *     
     */
    public void setDoseValue(DoseValueType value) {
        this.doseValue = value;
    }

    /**
     * Gets the value of the doseAssessmentMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoseAssessmentMethod() {
        return doseAssessmentMethod;
    }

    /**
     * Sets the value of the doseAssessmentMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoseAssessmentMethod(String value) {
        this.doseAssessmentMethod = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link FreeTextType }
     *     
     */
    public FreeTextType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeTextType }
     *     
     */
    public void setDescription(FreeTextType value) {
        this.description = value;
    }

}
