//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.medicalinformation;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HealthEffectsDiagnosedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HealthEffectsDiagnosedType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HealthEffectDiagnosed" type="{http://www.iaea.org/2012/IRIX/Format/MedicalInformation}HealthEffectDiagnosedType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HealthEffectsDiagnosedType", propOrder = {
    "healthEffectDiagnosed"
})
public class HealthEffectsDiagnosedType {

    @XmlElement(name = "HealthEffectDiagnosed")
    protected List<HealthEffectDiagnosedType> healthEffectDiagnosed;

    /**
     * Gets the value of the healthEffectDiagnosed property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the healthEffectDiagnosed property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHealthEffectDiagnosed().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HealthEffectDiagnosedType }
     * 
     * 
     */
    public List<HealthEffectDiagnosedType> getHealthEffectDiagnosed() {
        if (healthEffectDiagnosed == null) {
            healthEffectDiagnosed = new ArrayList<HealthEffectDiagnosedType>();
        }
        return this.healthEffectDiagnosed;
    }

}
