//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.medicalinformation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.iaea._2012.irix.format.base.FreeTextType;


/**
 * <p>Java class for HealthConsequencePrognosedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HealthConsequencePrognosedType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="TypeOfHealthConsequence" type="{http://www.iaea.org/2012/IRIX/Format/MedicalInformation}TypeOfHealthConsequenceType"/>
 *           &lt;element name="TypeOfHealthConsequenceDescription" type="{http://www.iaea.org/2012/IRIX/Format/Base}ShortStringType"/>
 *         &lt;/choice>
 *         &lt;element name="PrognosedOccurrence" type="{http://www.iaea.org/2012/IRIX/Format/MedicalInformation}PrognosedOccurrenceType"/>
 *         &lt;element name="Description" type="{http://www.iaea.org/2012/IRIX/Format/Base}FreeTextType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HealthConsequencePrognosedType", propOrder = {
    "typeOfHealthConsequence",
    "typeOfHealthConsequenceDescription",
    "prognosedOccurrence",
    "description"
})
public class HealthConsequencePrognosedType {

    @XmlElement(name = "TypeOfHealthConsequence")
    protected TypeOfHealthConsequenceType typeOfHealthConsequence;
    @XmlElement(name = "TypeOfHealthConsequenceDescription")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String typeOfHealthConsequenceDescription;
    @XmlElement(name = "PrognosedOccurrence", required = true)
    protected PrognosedOccurrenceType prognosedOccurrence;
    @XmlElement(name = "Description")
    protected FreeTextType description;

    /**
     * Gets the value of the typeOfHealthConsequence property.
     * 
     * @return
     *     possible object is
     *     {@link TypeOfHealthConsequenceType }
     *     
     */
    public TypeOfHealthConsequenceType getTypeOfHealthConsequence() {
        return typeOfHealthConsequence;
    }

    /**
     * Sets the value of the typeOfHealthConsequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeOfHealthConsequenceType }
     *     
     */
    public void setTypeOfHealthConsequence(TypeOfHealthConsequenceType value) {
        this.typeOfHealthConsequence = value;
    }

    /**
     * Gets the value of the typeOfHealthConsequenceDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOfHealthConsequenceDescription() {
        return typeOfHealthConsequenceDescription;
    }

    /**
     * Sets the value of the typeOfHealthConsequenceDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOfHealthConsequenceDescription(String value) {
        this.typeOfHealthConsequenceDescription = value;
    }

    /**
     * Gets the value of the prognosedOccurrence property.
     * 
     * @return
     *     possible object is
     *     {@link PrognosedOccurrenceType }
     *     
     */
    public PrognosedOccurrenceType getPrognosedOccurrence() {
        return prognosedOccurrence;
    }

    /**
     * Sets the value of the prognosedOccurrence property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrognosedOccurrenceType }
     *     
     */
    public void setPrognosedOccurrence(PrognosedOccurrenceType value) {
        this.prognosedOccurrence = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link FreeTextType }
     *     
     */
    public FreeTextType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeTextType }
     *     
     */
    public void setDescription(FreeTextType value) {
        this.description = value;
    }

}
