//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.medicalinformation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.iaea._2012.irix.format.base.FreeTextType;


/**
 * <p>Java class for HealthEffectDiagnosedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HealthEffectDiagnosedType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="TypeOfHealthEffect" type="{http://www.iaea.org/2012/IRIX/Format/MedicalInformation}TypeOfHealthEffectType"/>
 *           &lt;element name="TypeOfHealthEffectDescription" type="{http://www.iaea.org/2012/IRIX/Format/Base}ShortStringType"/>
 *         &lt;/choice>
 *         &lt;element name="DiagnosticResult" type="{http://www.iaea.org/2012/IRIX/Format/MedicalInformation}DiagnosticResultType"/>
 *         &lt;element name="Description" type="{http://www.iaea.org/2012/IRIX/Format/Base}FreeTextType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HealthEffectDiagnosedType", propOrder = {
    "typeOfHealthEffect",
    "typeOfHealthEffectDescription",
    "diagnosticResult",
    "description"
})
public class HealthEffectDiagnosedType {

    @XmlElement(name = "TypeOfHealthEffect")
    protected TypeOfHealthEffectType typeOfHealthEffect;
    @XmlElement(name = "TypeOfHealthEffectDescription")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String typeOfHealthEffectDescription;
    @XmlElement(name = "DiagnosticResult", required = true)
    protected DiagnosticResultType diagnosticResult;
    @XmlElement(name = "Description")
    protected FreeTextType description;

    /**
     * Gets the value of the typeOfHealthEffect property.
     * 
     * @return
     *     possible object is
     *     {@link TypeOfHealthEffectType }
     *     
     */
    public TypeOfHealthEffectType getTypeOfHealthEffect() {
        return typeOfHealthEffect;
    }

    /**
     * Sets the value of the typeOfHealthEffect property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeOfHealthEffectType }
     *     
     */
    public void setTypeOfHealthEffect(TypeOfHealthEffectType value) {
        this.typeOfHealthEffect = value;
    }

    /**
     * Gets the value of the typeOfHealthEffectDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOfHealthEffectDescription() {
        return typeOfHealthEffectDescription;
    }

    /**
     * Sets the value of the typeOfHealthEffectDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOfHealthEffectDescription(String value) {
        this.typeOfHealthEffectDescription = value;
    }

    /**
     * Gets the value of the diagnosticResult property.
     * 
     * @return
     *     possible object is
     *     {@link DiagnosticResultType }
     *     
     */
    public DiagnosticResultType getDiagnosticResult() {
        return diagnosticResult;
    }

    /**
     * Sets the value of the diagnosticResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiagnosticResultType }
     *     
     */
    public void setDiagnosticResult(DiagnosticResultType value) {
        this.diagnosticResult = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link FreeTextType }
     *     
     */
    public FreeTextType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeTextType }
     *     
     */
    public void setDescription(FreeTextType value) {
        this.description = value;
    }

}
