//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.medicalinformation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.iaea._2012.irix.format.base.InformationBlock;


/**
 * <p>Java class for MedicalInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MedicalInformationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iaea.org/2012/IRIX/Format/Base}InformationBlock">
 *       &lt;sequence>
 *         &lt;element name="PersonsDiagnosed" type="{http://www.iaea.org/2012/IRIX/Format/MedicalInformation}PersonsDiagnosedType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MedicalInformationType", propOrder = {
    "personsDiagnosed"
})
public class MedicalInformationType
    extends InformationBlock
{

    @XmlElement(name = "PersonsDiagnosed")
    protected PersonsDiagnosedType personsDiagnosed;

    /**
     * Gets the value of the personsDiagnosed property.
     * 
     * @return
     *     possible object is
     *     {@link PersonsDiagnosedType }
     *     
     */
    public PersonsDiagnosedType getPersonsDiagnosed() {
        return personsDiagnosed;
    }

    /**
     * Sets the value of the personsDiagnosed property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonsDiagnosedType }
     *     
     */
    public void setPersonsDiagnosed(PersonsDiagnosedType value) {
        this.personsDiagnosed = value;
    }

}
