//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.medicalinformation;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.iaea._2012.irix.format.medicalinformation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MedicalInformation_QNAME = new QName("http://www.iaea.org/2012/IRIX/Format/MedicalInformation", "MedicalInformation");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.iaea._2012.irix.format.medicalinformation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MedicalInformationType }
     * 
     */
    public MedicalInformationType createMedicalInformationType() {
        return new MedicalInformationType();
    }

    /**
     * Create an instance of {@link HealthEffectsDiagnosedType }
     * 
     */
    public HealthEffectsDiagnosedType createHealthEffectsDiagnosedType() {
        return new HealthEffectsDiagnosedType();
    }

    /**
     * Create an instance of {@link DoseValueType }
     * 
     */
    public DoseValueType createDoseValueType() {
        return new DoseValueType();
    }

    /**
     * Create an instance of {@link PersonDiagnosedType }
     * 
     */
    public PersonDiagnosedType createPersonDiagnosedType() {
        return new PersonDiagnosedType();
    }

    /**
     * Create an instance of {@link IdentityType }
     * 
     */
    public IdentityType createIdentityType() {
        return new IdentityType();
    }

    /**
     * Create an instance of {@link DoseAssessmentType }
     * 
     */
    public DoseAssessmentType createDoseAssessmentType() {
        return new DoseAssessmentType();
    }

    /**
     * Create an instance of {@link HealthConsequencePrognosedType }
     * 
     */
    public HealthConsequencePrognosedType createHealthConsequencePrognosedType() {
        return new HealthConsequencePrognosedType();
    }

    /**
     * Create an instance of {@link PersonsDiagnosedType }
     * 
     */
    public PersonsDiagnosedType createPersonsDiagnosedType() {
        return new PersonsDiagnosedType();
    }

    /**
     * Create an instance of {@link HealthEffectDiagnosedType }
     * 
     */
    public HealthEffectDiagnosedType createHealthEffectDiagnosedType() {
        return new HealthEffectDiagnosedType();
    }

    /**
     * Create an instance of {@link AssessedDoseType }
     * 
     */
    public AssessedDoseType createAssessedDoseType() {
        return new AssessedDoseType();
    }

    /**
     * Create an instance of {@link HealthConsequencesPrognosedType }
     * 
     */
    public HealthConsequencesPrognosedType createHealthConsequencesPrognosedType() {
        return new HealthConsequencesPrognosedType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MedicalInformationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iaea.org/2012/IRIX/Format/MedicalInformation", name = "MedicalInformation")
    public JAXBElement<MedicalInformationType> createMedicalInformation(MedicalInformationType value) {
        return new JAXBElement<MedicalInformationType>(_MedicalInformation_QNAME, MedicalInformationType.class, null, value);
    }

}
