//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.medicalinformation;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrognosedOccurrenceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PrognosedOccurrenceType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Negative"/>
 *     &lt;enumeration value="Possible"/>
 *     &lt;enumeration value="Probable"/>
 *     &lt;enumeration value="Definite"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PrognosedOccurrenceType")
@XmlEnum
public enum PrognosedOccurrenceType {

    @XmlEnumValue("Negative")
    NEGATIVE("Negative"),
    @XmlEnumValue("Possible")
    POSSIBLE("Possible"),
    @XmlEnumValue("Probable")
    PROBABLE("Probable"),
    @XmlEnumValue("Definite")
    DEFINITE("Definite");
    private final String value;

    PrognosedOccurrenceType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PrognosedOccurrenceType fromValue(String v) {
        for (PrognosedOccurrenceType c: PrognosedOccurrenceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
