//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.medicalinformation;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TypeOfHealthEffectType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TypeOfHealthEffectType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Acute Radiation Syndrome"/>
 *     &lt;enumeration value="Bone Marrow Depression"/>
 *     &lt;enumeration value="Cataract"/>
 *     &lt;enumeration value="Erythema"/>
 *     &lt;enumeration value="Necrosis"/>
 *     &lt;enumeration value="Pneumonitis"/>
 *     &lt;enumeration value="Ulceration"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TypeOfHealthEffectType")
@XmlEnum
public enum TypeOfHealthEffectType {

    @XmlEnumValue("Acute Radiation Syndrome")
    ACUTE_RADIATION_SYNDROME("Acute Radiation Syndrome"),
    @XmlEnumValue("Bone Marrow Depression")
    BONE_MARROW_DEPRESSION("Bone Marrow Depression"),
    @XmlEnumValue("Cataract")
    CATARACT("Cataract"),
    @XmlEnumValue("Erythema")
    ERYTHEMA("Erythema"),
    @XmlEnumValue("Necrosis")
    NECROSIS("Necrosis"),
    @XmlEnumValue("Pneumonitis")
    PNEUMONITIS("Pneumonitis"),
    @XmlEnumValue("Ulceration")
    ULCERATION("Ulceration");
    private final String value;

    TypeOfHealthEffectType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeOfHealthEffectType fromValue(String v) {
        for (TypeOfHealthEffectType c: TypeOfHealthEffectType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
