//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.medicalinformation;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TypeOfDoseType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TypeOfDoseType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Whole Body"/>
 *     &lt;enumeration value="Head/Neck"/>
 *     &lt;enumeration value="Eye/Lens"/>
 *     &lt;enumeration value="Thyroid"/>
 *     &lt;enumeration value="Skin"/>
 *     &lt;enumeration value="Breast/Chest"/>
 *     &lt;enumeration value="Bone Marrow"/>
 *     &lt;enumeration value="Colon"/>
 *     &lt;enumeration value="Gonads"/>
 *     &lt;enumeration value="Lung"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TypeOfDoseType")
@XmlEnum
public enum TypeOfDoseType {

    @XmlEnumValue("Whole Body")
    WHOLE_BODY("Whole Body"),
    @XmlEnumValue("Head/Neck")
    HEAD_NECK("Head/Neck"),
    @XmlEnumValue("Eye/Lens")
    EYE_LENS("Eye/Lens"),
    @XmlEnumValue("Thyroid")
    THYROID("Thyroid"),
    @XmlEnumValue("Skin")
    SKIN("Skin"),
    @XmlEnumValue("Breast/Chest")
    BREAST_CHEST("Breast/Chest"),
    @XmlEnumValue("Bone Marrow")
    BONE_MARROW("Bone Marrow"),
    @XmlEnumValue("Colon")
    COLON("Colon"),
    @XmlEnumValue("Gonads")
    GONADS("Gonads"),
    @XmlEnumValue("Lung")
    LUNG("Lung");
    private final String value;

    TypeOfDoseType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeOfDoseType fromValue(String v) {
        for (TypeOfDoseType c: TypeOfDoseType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
