//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.19 at 02:22:10 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.iaea.org/2012/IRIX/Format/Annexes", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.iaea._2012.irix.format.annexes;
