//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.responseactions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.iaea._2012.irix.format.base.AngleType;
import org.iaea._2012.irix.format.base.LengthType;


/**
 * <p>Java class for AreaSectorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AreaSectorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FromAngle" type="{http://www.iaea.org/2012/IRIX/Format/Base}AngleType"/>
 *         &lt;element name="TillAngle" type="{http://www.iaea.org/2012/IRIX/Format/Base}AngleType"/>
 *         &lt;element name="InnerRadius" type="{http://www.iaea.org/2012/IRIX/Format/Base}LengthType"/>
 *         &lt;element name="OuterRadius" type="{http://www.iaea.org/2012/IRIX/Format/Base}LengthType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AreaSectorType", propOrder = {
    "fromAngle",
    "tillAngle",
    "innerRadius",
    "outerRadius"
})
public class AreaSectorType {

    @XmlElement(name = "FromAngle", required = true)
    protected AngleType fromAngle;
    @XmlElement(name = "TillAngle", required = true)
    protected AngleType tillAngle;
    @XmlElement(name = "InnerRadius", required = true)
    protected LengthType innerRadius;
    @XmlElement(name = "OuterRadius", required = true)
    protected LengthType outerRadius;

    /**
     * Gets the value of the fromAngle property.
     * 
     * @return
     *     possible object is
     *     {@link AngleType }
     *     
     */
    public AngleType getFromAngle() {
        return fromAngle;
    }

    /**
     * Sets the value of the fromAngle property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngleType }
     *     
     */
    public void setFromAngle(AngleType value) {
        this.fromAngle = value;
    }

    /**
     * Gets the value of the tillAngle property.
     * 
     * @return
     *     possible object is
     *     {@link AngleType }
     *     
     */
    public AngleType getTillAngle() {
        return tillAngle;
    }

    /**
     * Sets the value of the tillAngle property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngleType }
     *     
     */
    public void setTillAngle(AngleType value) {
        this.tillAngle = value;
    }

    /**
     * Gets the value of the innerRadius property.
     * 
     * @return
     *     possible object is
     *     {@link LengthType }
     *     
     */
    public LengthType getInnerRadius() {
        return innerRadius;
    }

    /**
     * Sets the value of the innerRadius property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthType }
     *     
     */
    public void setInnerRadius(LengthType value) {
        this.innerRadius = value;
    }

    /**
     * Gets the value of the outerRadius property.
     * 
     * @return
     *     possible object is
     *     {@link LengthType }
     *     
     */
    public LengthType getOuterRadius() {
        return outerRadius;
    }

    /**
     * Sets the value of the outerRadius property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthType }
     *     
     */
    public void setOuterRadius(LengthType value) {
        this.outerRadius = value;
    }

}
