//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.responseactions;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.iaea._2012.irix.format.responseactions package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ResponseActions_QNAME = new QName("http://www.iaea.org/2012/IRIX/Format/ResponseActions", "ResponseActions");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.iaea._2012.irix.format.responseactions
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResponseActionsType }
     * 
     */
    public ResponseActionsType createResponseActionsType() {
        return new ResponseActionsType();
    }

    /**
     * Create an instance of {@link AreaSectorType }
     * 
     */
    public AreaSectorType createAreaSectorType() {
        return new AreaSectorType();
    }

    /**
     * Create an instance of {@link ProtectiveActionType }
     * 
     */
    public ProtectiveActionType createProtectiveActionType() {
        return new ProtectiveActionType();
    }

    /**
     * Create an instance of {@link ProtectiveActionsType }
     * 
     */
    public ProtectiveActionsType createProtectiveActionsType() {
        return new ProtectiveActionsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseActionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iaea.org/2012/IRIX/Format/ResponseActions", name = "ResponseActions")
    public JAXBElement<ResponseActionsType> createResponseActions(ResponseActionsType value) {
        return new JAXBElement<ResponseActionsType>(_ResponseActions_QNAME, ResponseActionsType.class, null, value);
    }

}
