//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.responseactions;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.iaea._2012.irix.format.base.YesNoType;


/**
 * <p>Java class for ProtectiveActionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProtectiveActionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProtectiveActionsTakenOrPlanned" type="{http://www.iaea.org/2012/IRIX/Format/Base}YesNoType"/>
 *         &lt;element name="ProtectiveAction" type="{http://www.iaea.org/2012/IRIX/Format/ResponseActions}ProtectiveActionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProtectiveActionsType", propOrder = {
    "protectiveActionsTakenOrPlanned",
    "protectiveAction"
})
public class ProtectiveActionsType {

    @XmlElement(name = "ProtectiveActionsTakenOrPlanned", required = true)
    protected YesNoType protectiveActionsTakenOrPlanned;
    @XmlElement(name = "ProtectiveAction")
    protected List<ProtectiveActionType> protectiveAction;

    /**
     * Gets the value of the protectiveActionsTakenOrPlanned property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getProtectiveActionsTakenOrPlanned() {
        return protectiveActionsTakenOrPlanned;
    }

    /**
     * Sets the value of the protectiveActionsTakenOrPlanned property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setProtectiveActionsTakenOrPlanned(YesNoType value) {
        this.protectiveActionsTakenOrPlanned = value;
    }

    /**
     * Gets the value of the protectiveAction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the protectiveAction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProtectiveAction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProtectiveActionType }
     * 
     * 
     */
    public List<ProtectiveActionType> getProtectiveAction() {
        if (protectiveAction == null) {
            protectiveAction = new ArrayList<ProtectiveActionType>();
        }
        return this.protectiveAction;
    }

}
