//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.responseactions;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TypeOfProtectiveActionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TypeOfProtectiveActionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Stable Iodine Prophylaxis"/>
 *     &lt;enumeration value="Sheltering"/>
 *     &lt;enumeration value="Evacuation"/>
 *     &lt;enumeration value="Food Restrictions"/>
 *     &lt;enumeration value="Restriction on Water Use"/>
 *     &lt;enumeration value="Access Restrictions"/>
 *     &lt;enumeration value="Urgent Decontamination"/>
 *     &lt;enumeration value="Registration for Follow-Up"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TypeOfProtectiveActionType")
@XmlEnum
public enum TypeOfProtectiveActionType {

    @XmlEnumValue("Stable Iodine Prophylaxis")
    STABLE_IODINE_PROPHYLAXIS("Stable Iodine Prophylaxis"),
    @XmlEnumValue("Sheltering")
    SHELTERING("Sheltering"),
    @XmlEnumValue("Evacuation")
    EVACUATION("Evacuation"),
    @XmlEnumValue("Food Restrictions")
    FOOD_RESTRICTIONS("Food Restrictions"),
    @XmlEnumValue("Restriction on Water Use")
    RESTRICTION_ON_WATER_USE("Restriction on Water Use"),
    @XmlEnumValue("Access Restrictions")
    ACCESS_RESTRICTIONS("Access Restrictions"),
    @XmlEnumValue("Urgent Decontamination")
    URGENT_DECONTAMINATION("Urgent Decontamination"),
    @XmlEnumValue("Registration for Follow-Up")
    REGISTRATION_FOR_FOLLOW_UP("Registration for Follow-Up");
    private final String value;

    TypeOfProtectiveActionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeOfProtectiveActionType fromValue(String v) {
        for (TypeOfProtectiveActionType c: TypeOfProtectiveActionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
