//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.eventinformation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.iaea._2012.irix.format.base.FreeTextType;


/**
 * <p>Java class for CoreStateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CoreStateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Criticality" type="{http://www.iaea.org/2012/IRIX/Format/EventInformation}CriticalityType" minOccurs="0"/>
 *         &lt;element name="SevereDamageToFuel" type="{http://www.iaea.org/2012/IRIX/Format/EventInformation}SevereDamageToFuelType" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.iaea.org/2012/IRIX/Format/Base}FreeTextType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CoreStateType", propOrder = {
    "criticality",
    "severeDamageToFuel",
    "description"
})
public class CoreStateType {

    @XmlElement(name = "Criticality")
    protected CriticalityType criticality;
    @XmlElement(name = "SevereDamageToFuel")
    protected SevereDamageToFuelType severeDamageToFuel;
    @XmlElement(name = "Description")
    protected FreeTextType description;

    /**
     * Gets the value of the criticality property.
     * 
     * @return
     *     possible object is
     *     {@link CriticalityType }
     *     
     */
    public CriticalityType getCriticality() {
        return criticality;
    }

    /**
     * Sets the value of the criticality property.
     * 
     * @param value
     *     allowed object is
     *     {@link CriticalityType }
     *     
     */
    public void setCriticality(CriticalityType value) {
        this.criticality = value;
    }

    /**
     * Gets the value of the severeDamageToFuel property.
     * 
     * @return
     *     possible object is
     *     {@link SevereDamageToFuelType }
     *     
     */
    public SevereDamageToFuelType getSevereDamageToFuel() {
        return severeDamageToFuel;
    }

    /**
     * Sets the value of the severeDamageToFuel property.
     * 
     * @param value
     *     allowed object is
     *     {@link SevereDamageToFuelType }
     *     
     */
    public void setSevereDamageToFuel(SevereDamageToFuelType value) {
        this.severeDamageToFuel = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link FreeTextType }
     *     
     */
    public FreeTextType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeTextType }
     *     
     */
    public void setDescription(FreeTextType value) {
        this.description = value;
    }

}
