//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.eventinformation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CriticalityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CriticalityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Status" type="{http://www.iaea.org/2012/IRIX/Format/EventInformation}CriticalityStatusValueType"/>
 *         &lt;element name="StoppedAt" type="{http://www.iaea.org/2012/IRIX/Format/Base}DateTimeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CriticalityType", propOrder = {
    "status",
    "stoppedAt"
})
public class CriticalityType {

    @XmlElement(name = "Status", required = true)
    protected CriticalityStatusValueType status;
    @XmlElement(name = "StoppedAt")
    protected XMLGregorianCalendar stoppedAt;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link CriticalityStatusValueType }
     *     
     */
    public CriticalityStatusValueType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link CriticalityStatusValueType }
     *     
     */
    public void setStatus(CriticalityStatusValueType value) {
        this.status = value;
    }

    /**
     * Gets the value of the stoppedAt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStoppedAt() {
        return stoppedAt;
    }

    /**
     * Sets the value of the stoppedAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStoppedAt(XMLGregorianCalendar value) {
        this.stoppedAt = value;
    }

}
