//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.eventinformation;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CriticalityStatusValueType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CriticalityStatusValueType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Stopped"/>
 *     &lt;enumeration value="Continuing"/>
 *     &lt;enumeration value="Unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CriticalityStatusValueType")
@XmlEnum
public enum CriticalityStatusValueType {

    @XmlEnumValue("Stopped")
    STOPPED("Stopped"),
    @XmlEnumValue("Continuing")
    CONTINUING("Continuing"),
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown");
    private final String value;

    CriticalityStatusValueType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CriticalityStatusValueType fromValue(String v) {
        for (CriticalityStatusValueType c: CriticalityStatusValueType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
