//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.eventinformation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;
import org.iaea._2012.irix.format.base.YesNoType;


/**
 * <p>Java class for DateAndTimeOfEventType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DateAndTimeOfEventType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.iaea.org/2012/IRIX/Format/Base>DateTimeType">
 *       &lt;attribute name="IsEstimate" type="{http://www.iaea.org/2012/IRIX/Format/Base}YesNoType" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DateAndTimeOfEventType", propOrder = {
    "value"
})
public class DateAndTimeOfEventType {

    @XmlValue
    protected XMLGregorianCalendar value;
    @XmlAttribute(name = "IsEstimate")
    protected YesNoType isEstimate;

    /**
     * 
     * 				A date and time in a prescribed format. Note that the time
     * 				zone is
     * 				required and set to Z (UTC).
     * 				
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;html:ul xmlns:html="http://www.w3.org/1999/xhtml" xmlns:base="http://www.iaea.org/2012/IRIX/Format/Base" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;html:li&gt;Four digits for the year (\d{4})&lt;/html:li&gt;&lt;html:li&gt;Two digits for the month&lt;/html:li&gt;&lt;html:li&gt;Two digits for the day&lt;/html:li&gt;&lt;html:li&gt;A time seperator 'T'&lt;/html:li&gt;&lt;html:li&gt;Two digits for the 24-hour, so 7 AM is written as '07' and
     * 						7 PM is written as '19'
     * 					&lt;/html:li&gt;&lt;html:li&gt;Two digits for the minutes&lt;/html:li&gt;&lt;html:li&gt;Two digits for the seconds&lt;/html:li&gt;&lt;html:li&gt;A 'Z' specifying UTC time&lt;/html:li&gt;
     * 				&lt;/html:ul&gt;
     * </pre>
     * 
     * 				Example: 2010-04-12T12:56:23Z for April 12th, 2010 at 12:56:23h UTC.
     * 			
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValue(XMLGregorianCalendar value) {
        this.value = value;
    }

    /**
     * Gets the value of the isEstimate property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getIsEstimate() {
        return isEstimate;
    }

    /**
     * Sets the value of the isEstimate property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setIsEstimate(YesNoType value) {
        this.isEstimate = value;
    }

}
