//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.eventinformation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import org.iaea._2012.irix.format.base.FreeTextType;


/**
 * <p>Java class for EmergencyClassificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmergencyClassificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="EmergencyClass" type="{http://www.iaea.org/2012/IRIX/Format/EventInformation}EmergencyClassValueType"/>
 *           &lt;element name="EmergencyClassDescription" type="{http://www.iaea.org/2012/IRIX/Format/Base}ShortStringType"/>
 *         &lt;/choice>
 *         &lt;element name="DateAndTimeOfDeclaration" type="{http://www.iaea.org/2012/IRIX/Format/Base}DateTimeType" minOccurs="0"/>
 *         &lt;element name="BasisForDeclaration" type="{http://www.iaea.org/2012/IRIX/Format/Base}FreeTextType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmergencyClassificationType", propOrder = {
    "emergencyClass",
    "emergencyClassDescription",
    "dateAndTimeOfDeclaration",
    "basisForDeclaration"
})
public class EmergencyClassificationType {

    @XmlElement(name = "EmergencyClass")
    protected EmergencyClassValueType emergencyClass;
    @XmlElement(name = "EmergencyClassDescription")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String emergencyClassDescription;
    @XmlElement(name = "DateAndTimeOfDeclaration")
    protected XMLGregorianCalendar dateAndTimeOfDeclaration;
    @XmlElement(name = "BasisForDeclaration")
    protected FreeTextType basisForDeclaration;

    /**
     * Gets the value of the emergencyClass property.
     * 
     * @return
     *     possible object is
     *     {@link EmergencyClassValueType }
     *     
     */
    public EmergencyClassValueType getEmergencyClass() {
        return emergencyClass;
    }

    /**
     * Sets the value of the emergencyClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmergencyClassValueType }
     *     
     */
    public void setEmergencyClass(EmergencyClassValueType value) {
        this.emergencyClass = value;
    }

    /**
     * Gets the value of the emergencyClassDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmergencyClassDescription() {
        return emergencyClassDescription;
    }

    /**
     * Sets the value of the emergencyClassDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmergencyClassDescription(String value) {
        this.emergencyClassDescription = value;
    }

    /**
     * Gets the value of the dateAndTimeOfDeclaration property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateAndTimeOfDeclaration() {
        return dateAndTimeOfDeclaration;
    }

    /**
     * Sets the value of the dateAndTimeOfDeclaration property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateAndTimeOfDeclaration(XMLGregorianCalendar value) {
        this.dateAndTimeOfDeclaration = value;
    }

    /**
     * Gets the value of the basisForDeclaration property.
     * 
     * @return
     *     possible object is
     *     {@link FreeTextType }
     *     
     */
    public FreeTextType getBasisForDeclaration() {
        return basisForDeclaration;
    }

    /**
     * Sets the value of the basisForDeclaration property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeTextType }
     *     
     */
    public void setBasisForDeclaration(FreeTextType value) {
        this.basisForDeclaration = value;
    }

}
