//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.eventinformation;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EmergencyClassValueType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EmergencyClassValueType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="General Emergency"/>
 *     &lt;enumeration value="Site Area Emergency"/>
 *     &lt;enumeration value="Facility Emergency"/>
 *     &lt;enumeration value="Alert"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EmergencyClassValueType")
@XmlEnum
public enum EmergencyClassValueType {

    @XmlEnumValue("General Emergency")
    GENERAL_EMERGENCY("General Emergency"),
    @XmlEnumValue("Site Area Emergency")
    SITE_AREA_EMERGENCY("Site Area Emergency"),
    @XmlEnumValue("Facility Emergency")
    FACILITY_EMERGENCY("Facility Emergency"),
    @XmlEnumValue("Alert")
    ALERT("Alert");
    private final String value;

    EmergencyClassValueType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EmergencyClassValueType fromValue(String v) {
        for (EmergencyClassValueType c: EmergencyClassValueType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
