//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.eventinformation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.iaea._2012.irix.format.base.FreeTextType;


/**
 * <p>Java class for INESClassificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="INESClassificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="INESLevel" type="{http://www.iaea.org/2012/IRIX/Format/EventInformation}INESValueType"/>
 *         &lt;element name="StatusOfClassification" type="{http://www.iaea.org/2012/IRIX/Format/EventInformation}INESStatusType"/>
 *         &lt;element name="DateAndTimeOfClassification" type="{http://www.iaea.org/2012/IRIX/Format/Base}DateTimeType" minOccurs="0"/>
 *         &lt;element name="BasisForClassification" type="{http://www.iaea.org/2012/IRIX/Format/Base}FreeTextType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "INESClassificationType", propOrder = {
    "inesLevel",
    "statusOfClassification",
    "dateAndTimeOfClassification",
    "basisForClassification"
})
public class INESClassificationType {

    @XmlElement(name = "INESLevel", required = true)
    protected INESValueType inesLevel;
    @XmlElement(name = "StatusOfClassification", required = true)
    protected INESStatusType statusOfClassification;
    @XmlElement(name = "DateAndTimeOfClassification")
    protected XMLGregorianCalendar dateAndTimeOfClassification;
    @XmlElement(name = "BasisForClassification")
    protected FreeTextType basisForClassification;

    /**
     * Gets the value of the inesLevel property.
     * 
     * @return
     *     possible object is
     *     {@link INESValueType }
     *     
     */
    public INESValueType getINESLevel() {
        return inesLevel;
    }

    /**
     * Sets the value of the inesLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link INESValueType }
     *     
     */
    public void setINESLevel(INESValueType value) {
        this.inesLevel = value;
    }

    /**
     * Gets the value of the statusOfClassification property.
     * 
     * @return
     *     possible object is
     *     {@link INESStatusType }
     *     
     */
    public INESStatusType getStatusOfClassification() {
        return statusOfClassification;
    }

    /**
     * Sets the value of the statusOfClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link INESStatusType }
     *     
     */
    public void setStatusOfClassification(INESStatusType value) {
        this.statusOfClassification = value;
    }

    /**
     * Gets the value of the dateAndTimeOfClassification property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateAndTimeOfClassification() {
        return dateAndTimeOfClassification;
    }

    /**
     * Sets the value of the dateAndTimeOfClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateAndTimeOfClassification(XMLGregorianCalendar value) {
        this.dateAndTimeOfClassification = value;
    }

    /**
     * Gets the value of the basisForClassification property.
     * 
     * @return
     *     possible object is
     *     {@link FreeTextType }
     *     
     */
    public FreeTextType getBasisForClassification() {
        return basisForClassification;
    }

    /**
     * Sets the value of the basisForClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeTextType }
     *     
     */
    public void setBasisForClassification(FreeTextType value) {
        this.basisForClassification = value;
    }

}
