//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.eventinformation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.iaea._2012.irix.format.base.FreeTextType;
import org.iaea._2012.irix.format.locations.LocationOrLocationRefType;


/**
 * <p>Java class for ObjectInvolvedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObjectInvolvedType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="TypeOfObjectOrActivity" type="{http://www.iaea.org/2012/IRIX/Format/EventInformation}TypeOfObjectOrActivityType"/>
 *           &lt;element name="TypeOfObjectOrActivityDescription" type="{http://www.iaea.org/2012/IRIX/Format/Base}ShortStringType"/>
 *         &lt;/choice>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element ref="{http://www.iaea.org/2012/IRIX/Format/Locations}Location" minOccurs="0"/>
 *         &lt;element name="SourceCharacteristics" type="{http://www.iaea.org/2012/IRIX/Format/EventInformation}RadioactiveSourcesType" minOccurs="0"/>
 *         &lt;element name="ReactorCharacteristics" type="{http://www.iaea.org/2012/IRIX/Format/EventInformation}ReactorCharacteristicsType" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.iaea.org/2012/IRIX/Format/Base}FreeTextType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjectInvolvedType", propOrder = {
    "typeOfObjectOrActivity",
    "typeOfObjectOrActivityDescription",
    "name",
    "location",
    "sourceCharacteristics",
    "reactorCharacteristics",
    "description"
})
public class ObjectInvolvedType {

    @XmlElement(name = "TypeOfObjectOrActivity")
    protected TypeOfObjectOrActivityType typeOfObjectOrActivity;
    @XmlElement(name = "TypeOfObjectOrActivityDescription")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String typeOfObjectOrActivityDescription;
    @XmlElement(name = "Name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String name;
    @XmlElement(name = "Location", namespace = "http://www.iaea.org/2012/IRIX/Format/Locations")
    protected LocationOrLocationRefType location;
    @XmlElement(name = "SourceCharacteristics")
    protected RadioactiveSourcesType sourceCharacteristics;
    @XmlElement(name = "ReactorCharacteristics")
    protected ReactorCharacteristicsType reactorCharacteristics;
    @XmlElement(name = "Description")
    protected FreeTextType description;

    /**
     * Gets the value of the typeOfObjectOrActivity property.
     * 
     * @return
     *     possible object is
     *     {@link TypeOfObjectOrActivityType }
     *     
     */
    public TypeOfObjectOrActivityType getTypeOfObjectOrActivity() {
        return typeOfObjectOrActivity;
    }

    /**
     * Sets the value of the typeOfObjectOrActivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeOfObjectOrActivityType }
     *     
     */
    public void setTypeOfObjectOrActivity(TypeOfObjectOrActivityType value) {
        this.typeOfObjectOrActivity = value;
    }

    /**
     * Gets the value of the typeOfObjectOrActivityDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOfObjectOrActivityDescription() {
        return typeOfObjectOrActivityDescription;
    }

    /**
     * Sets the value of the typeOfObjectOrActivityDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOfObjectOrActivityDescription(String value) {
        this.typeOfObjectOrActivityDescription = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;html:p xmlns:html="http://www.w3.org/1999/xhtml" xmlns:base="http://www.iaea.org/2012/IRIX/Format/Base" xmlns:event="http://www.iaea.org/2012/IRIX/Format/EventInformation" xmlns:loc="http://www.iaea.org/2012/IRIX/Format/Locations" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;
     * 							Contains information on the location of the object (e.g. installation, source etc) involved.
     * 						&lt;/html:p&gt;
     * </pre>
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;html:p xmlns:html="http://www.w3.org/1999/xhtml" xmlns:base="http://www.iaea.org/2012/IRIX/Format/Base" xmlns:event="http://www.iaea.org/2012/IRIX/Format/EventInformation" xmlns:loc="http://www.iaea.org/2012/IRIX/Format/Locations" xmlns:xsd="http://www.w3.org/2001/XMLSchema" class="note"&gt;
     * 							For the structure of this element, see Locations section.
     * 						&lt;/html:p&gt;
     * </pre>
     * 
     * 					
     * 
     * @return
     *     possible object is
     *     {@link LocationOrLocationRefType }
     *     
     */
    public LocationOrLocationRefType getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationOrLocationRefType }
     *     
     */
    public void setLocation(LocationOrLocationRefType value) {
        this.location = value;
    }

    /**
     * Gets the value of the sourceCharacteristics property.
     * 
     * @return
     *     possible object is
     *     {@link RadioactiveSourcesType }
     *     
     */
    public RadioactiveSourcesType getSourceCharacteristics() {
        return sourceCharacteristics;
    }

    /**
     * Sets the value of the sourceCharacteristics property.
     * 
     * @param value
     *     allowed object is
     *     {@link RadioactiveSourcesType }
     *     
     */
    public void setSourceCharacteristics(RadioactiveSourcesType value) {
        this.sourceCharacteristics = value;
    }

    /**
     * Gets the value of the reactorCharacteristics property.
     * 
     * @return
     *     possible object is
     *     {@link ReactorCharacteristicsType }
     *     
     */
    public ReactorCharacteristicsType getReactorCharacteristics() {
        return reactorCharacteristics;
    }

    /**
     * Sets the value of the reactorCharacteristics property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReactorCharacteristicsType }
     *     
     */
    public void setReactorCharacteristics(ReactorCharacteristicsType value) {
        this.reactorCharacteristics = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link FreeTextType }
     *     
     */
    public FreeTextType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeTextType }
     *     
     */
    public void setDescription(FreeTextType value) {
        this.description = value;
    }

}
