//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.eventinformation;

import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for RadioactiveSourceNuclideType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RadioactiveSourceNuclideType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.iaea.org/2012/IRIX/Format/EventInformation}NuclideInfo"/>
 *         &lt;element name="Activity" type="{http://www.iaea.org/2012/IRIX/Format/EventInformation}ActivityType" minOccurs="0"/>
 *         &lt;element name="ReferenceDateAndTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RadioactiveSourceNuclideType", propOrder = {
    "nuclideInfo",
    "activity",
    "referenceDateAndTime"
})
public class RadioactiveSourceNuclideType {

    @XmlElementRef(name = "NuclideInfo", namespace = "http://www.iaea.org/2012/IRIX/Format/EventInformation", type = JAXBElement.class)
    protected JAXBElement<?> nuclideInfo;
    @XmlElement(name = "Activity")
    protected ActivityType activity;
    @XmlElement(name = "ReferenceDateAndTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar referenceDateAndTime;

    /**
     * 
     * 						Nuclide(s) contained in the source.
     * 					
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     {@link JAXBElement }{@code <}{@link NuclideCombinationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link List }{@code <}{@link String }{@code >}{@code >}
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<?> getNuclideInfo() {
        return nuclideInfo;
    }

    /**
     * Sets the value of the nuclideInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     {@link JAXBElement }{@code <}{@link NuclideCombinationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link List }{@code <}{@link String }{@code >}{@code >}
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setNuclideInfo(JAXBElement<?> value) {
        this.nuclideInfo = value;
    }

    /**
     * Gets the value of the activity property.
     * 
     * @return
     *     possible object is
     *     {@link ActivityType }
     *     
     */
    public ActivityType getActivity() {
        return activity;
    }

    /**
     * Sets the value of the activity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivityType }
     *     
     */
    public void setActivity(ActivityType value) {
        this.activity = value;
    }

    /**
     * Gets the value of the referenceDateAndTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReferenceDateAndTime() {
        return referenceDateAndTime;
    }

    /**
     * Sets the value of the referenceDateAndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReferenceDateAndTime(XMLGregorianCalendar value) {
        this.referenceDateAndTime = value;
    }

}
