//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.eventinformation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.iaea._2012.irix.format.base.FreeTextType;
import org.iaea._2012.irix.format.base.YesNoUnknownType;


/**
 * <p>Java class for RadioactiveSourceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RadioactiveSourceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Sealed" type="{http://www.iaea.org/2012/IRIX/Format/Base}YesNoUnknownType" minOccurs="0"/>
 *         &lt;element name="Shielded" type="{http://www.iaea.org/2012/IRIX/Format/Base}YesNoUnknownType" minOccurs="0"/>
 *         &lt;element name="Nuclides" type="{http://www.iaea.org/2012/IRIX/Format/EventInformation}RadioactiveSourceNuclidesType"/>
 *         &lt;element name="Description" type="{http://www.iaea.org/2012/IRIX/Format/Base}FreeTextType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RadioactiveSourceType", propOrder = {
    "sealed",
    "shielded",
    "nuclides",
    "description"
})
public class RadioactiveSourceType {

    @XmlElement(name = "Sealed")
    protected YesNoUnknownType sealed;
    @XmlElement(name = "Shielded")
    protected YesNoUnknownType shielded;
    @XmlElement(name = "Nuclides", required = true)
    protected RadioactiveSourceNuclidesType nuclides;
    @XmlElement(name = "Description")
    protected FreeTextType description;

    /**
     * Gets the value of the sealed property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoUnknownType }
     *     
     */
    public YesNoUnknownType getSealed() {
        return sealed;
    }

    /**
     * Sets the value of the sealed property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoUnknownType }
     *     
     */
    public void setSealed(YesNoUnknownType value) {
        this.sealed = value;
    }

    /**
     * Gets the value of the shielded property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoUnknownType }
     *     
     */
    public YesNoUnknownType getShielded() {
        return shielded;
    }

    /**
     * Sets the value of the shielded property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoUnknownType }
     *     
     */
    public void setShielded(YesNoUnknownType value) {
        this.shielded = value;
    }

    /**
     * Gets the value of the nuclides property.
     * 
     * @return
     *     possible object is
     *     {@link RadioactiveSourceNuclidesType }
     *     
     */
    public RadioactiveSourceNuclidesType getNuclides() {
        return nuclides;
    }

    /**
     * Sets the value of the nuclides property.
     * 
     * @param value
     *     allowed object is
     *     {@link RadioactiveSourceNuclidesType }
     *     
     */
    public void setNuclides(RadioactiveSourceNuclidesType value) {
        this.nuclides = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link FreeTextType }
     *     
     */
    public FreeTextType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeTextType }
     *     
     */
    public void setDescription(FreeTextType value) {
        this.description = value;
    }

}
