//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.eventinformation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for SevereDamageToFuelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SevereDamageToFuelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Occurrence" type="{http://www.iaea.org/2012/IRIX/Format/EventInformation}SevereDamageToFuelOccurrenceType"/>
 *         &lt;element name="TimeOfOccurrence" type="{http://www.iaea.org/2012/IRIX/Format/Base}DateTimeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SevereDamageToFuelType", propOrder = {
    "occurrence",
    "timeOfOccurrence"
})
public class SevereDamageToFuelType {

    @XmlElement(name = "Occurrence", required = true)
    protected SevereDamageToFuelOccurrenceType occurrence;
    @XmlElement(name = "TimeOfOccurrence")
    protected XMLGregorianCalendar timeOfOccurrence;

    /**
     * Gets the value of the occurrence property.
     * 
     * @return
     *     possible object is
     *     {@link SevereDamageToFuelOccurrenceType }
     *     
     */
    public SevereDamageToFuelOccurrenceType getOccurrence() {
        return occurrence;
    }

    /**
     * Sets the value of the occurrence property.
     * 
     * @param value
     *     allowed object is
     *     {@link SevereDamageToFuelOccurrenceType }
     *     
     */
    public void setOccurrence(SevereDamageToFuelOccurrenceType value) {
        this.occurrence = value;
    }

    /**
     * Gets the value of the timeOfOccurrence property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeOfOccurrence() {
        return timeOfOccurrence;
    }

    /**
     * Sets the value of the timeOfOccurrence property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeOfOccurrence(XMLGregorianCalendar value) {
        this.timeOfOccurrence = value;
    }

}
