//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.eventinformation;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrendType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TrendType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Getting Better"/>
 *     &lt;enumeration value="Stable"/>
 *     &lt;enumeration value="Getting Worse"/>
 *     &lt;enumeration value="Unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TrendType")
@XmlEnum
public enum TrendType {

    @XmlEnumValue("Getting Better")
    GETTING_BETTER("Getting Better"),
    @XmlEnumValue("Stable")
    STABLE("Stable"),
    @XmlEnumValue("Getting Worse")
    GETTING_WORSE("Getting Worse"),
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown");
    private final String value;

    TrendType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TrendType fromValue(String v) {
        for (TrendType c: TrendType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
