//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.14 at 09:56:57 AM CET 
//


package org.iaea._2012.irix.format.eventinformation;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TypeOfObjectOrActivityType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TypeOfObjectOrActivityType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Nuclear Power Plant"/>
 *     &lt;enumeration value="Fuel Fabrication"/>
 *     &lt;enumeration value="Enrichment"/>
 *     &lt;enumeration value="Spent Fuel Storage"/>
 *     &lt;enumeration value="Spent Fuel Transport"/>
 *     &lt;enumeration value="Fuel Reprocessing"/>
 *     &lt;enumeration value="Research Reactor"/>
 *     &lt;enumeration value="Marine Reactor"/>
 *     &lt;enumeration value="Manufacture of Radioisotopes"/>
 *     &lt;enumeration value="Waste Treatment"/>
 *     &lt;enumeration value="Irradiation Facility"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TypeOfObjectOrActivityType")
@XmlEnum
public enum TypeOfObjectOrActivityType {

    @XmlEnumValue("Nuclear Power Plant")
    NUCLEAR_POWER_PLANT("Nuclear Power Plant"),
    @XmlEnumValue("Fuel Fabrication")
    FUEL_FABRICATION("Fuel Fabrication"),
    @XmlEnumValue("Enrichment")
    ENRICHMENT("Enrichment"),
    @XmlEnumValue("Spent Fuel Storage")
    SPENT_FUEL_STORAGE("Spent Fuel Storage"),
    @XmlEnumValue("Spent Fuel Transport")
    SPENT_FUEL_TRANSPORT("Spent Fuel Transport"),
    @XmlEnumValue("Fuel Reprocessing")
    FUEL_REPROCESSING("Fuel Reprocessing"),
    @XmlEnumValue("Research Reactor")
    RESEARCH_REACTOR("Research Reactor"),
    @XmlEnumValue("Marine Reactor")
    MARINE_REACTOR("Marine Reactor"),
    @XmlEnumValue("Manufacture of Radioisotopes")
    MANUFACTURE_OF_RADIOISOTOPES("Manufacture of Radioisotopes"),
    @XmlEnumValue("Waste Treatment")
    WASTE_TREATMENT("Waste Treatment"),
    @XmlEnumValue("Irradiation Facility")
    IRRADIATION_FACILITY("Irradiation Facility");
    private final String value;

    TypeOfObjectOrActivityType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeOfObjectOrActivityType fromValue(String v) {
        for (TypeOfObjectOrActivityType c: TypeOfObjectOrActivityType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
